---
settings:
  name: Release Notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Notes de version de la console NetApp
    url: "/index.html"
  - title: Changements récents
    url: "/whats-new.html"
  - title: Index des notes de publication
    url: "/release-notes-index.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
