---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.

[NOTE]
====
Les services suivants ont été abandonnés :

Mise en cache de périphérie:: Le service de mise en cache de périphérie a été supprimé le 7 août 2024.
Kubernetes:: La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.
Rapports de migration:: Le service de rapports de migration a été supprimé le 7 août 2024.
Résilience opérationnelle:: Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.
Assainissement:: Le service de remédiation a été supprimé le 22 avril 2024.


====


[[15-july-2026]]
== 15 juillet 2026



[[console-setup-and-administration]]
=== Configuration et administration de la console



==== Agent Console 4.9.0

La version 4.9.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité et des corrections de bugs.



==== Administration de la NetApp Console

.Prise en charge du contrôle d'accès basé sur les rôles pour Cloud Volumes ONTAP
La console prend en charge le contrôle d'accès basé sur les rôles pour Cloud Volumes ONTAP.

link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["En savoir plus sur le contrôle d'accès basé sur les rôles pour Cloud Volumes ONTAP"^].



[[14-july-2026]]
== 14 juillet 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP 9.19.1 RC

Vous pouvez désormais utiliser la NetApp Console pour déployer et gérer la version Release Candidate (RC) de Cloud Volumes ONTAP 9.19.1 dans Google Cloud. Cette version n'est pas disponible pour le déploiement et la mise à niveau dans Amazon Web Service (AWS) et Microsoft Azure (Azure).

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["En savoir plus sur cette version de Cloud Volumes ONTAP"^].



==== Prise en charge des machines virtuelles Google Cloud de nouvelle génération dans Cloud Volumes ONTAP HA

Avec la version 9.19.1, NetApp fait passer les déploiements Cloud Volumes ONTAP à haute disponibilité (HA) des machines virtuelles N2 aux machines virtuelles de nouvelle génération de la série Google Cloud C3 pour une expérience plus rapide et plus évolutive.


NOTE: Cette assistance s'applique uniquement aux déploiements HA à zone de disponibilité unique (AZ).

Vous pouvez désormais tirer parti des machines virtuelles de la série C3 lors du déploiement de Cloud Volumes ONTAP 9.19.1 et versions ultérieures sur Google Cloud. Ces machines offrent des performances améliorées et des limites de capacité plus élevées. Elles utilisent Google Virtual NIC (gVNIC) et des disques Hyperdisk Balanced pour des performances dynamiques sur les charges de travail intensives.

Si votre système Cloud Volumes ONTAP exécute la version 9.19.1 ou ultérieure, les packages préconfigurés que vous utilisez pour des déploiements simplifiés dans une seule zone de disponibilité utilisent automatiquement des machines virtuelles C3, tout en vous permettant de personnaliser les paramètres d'IOPS et de débit en fonction des besoins de votre charge de travail. De même, lors de la création d'agrégats, vous pouvez ajouter des disques Zonal Hyperdisk Balanced pour obtenir de meilleures performances et une meilleure évolutivité sur Google Cloud. Vous pouvez également sélectionner les variantes LSSD des machines de la série C3 pour une prise en charge par défaut du Flash Cache.

Notez ces points :

* Dans vos déploiements Cloud Volumes ONTAP, vous ne pouvez pas changer des machines virtuelles C3 en machines virtuelles de la série N2 et inversement. Cependant, vous pouvez changer de type d'instance parmi les différentes variantes de la famille C3.
+

NOTE: Le changement de type d'instance au sein de la famille C3 peut prendre plus de temps en fonction du nombre de disques de données connectés. Planifiez votre configuration à l'avance pour éviter tout impact sur les performances.

* Lors du changement de type d'instance, si vous sélectionnez c3-standard-44 ou c3-standard-88 et leurs variantes SSD locales (LSSD) comme machine virtuelle cible, le niveau de réseau de sortie du service réseau Google _Tier-1_ est appliqué automatiquement. Si vous revenez à une autre variante C3, le niveau de réseau de sortie est défini sur _Standard_.
+

NOTE: Le passage au niveau _Tier-1_ du réseau de sortie engendre des coûts supplémentaires. Prévoyez le déploiement et la mise à niveau en conséquence.

* Si vous sélectionnez les variantes LSSD de C3, le cache Flash est activé par défaut. Vous ne pouvez pas changer de variante LSSD de C3 dans votre déploiement Cloud Volumes ONTAP, même si la variante cible prend en charge le cache Flash.
* Sur vos machines virtuelles C3, vous pouvez ajouter des volumes aux agrégats nouveaux et existants.
* Lors de la réplication d'un système Cloud Volumes ONTAP avec un type de VM N2 vers un type de VM C3, le type de disque est défini par défaut sur Hyperdisk Balanced.
* Vous pouvez modifier les paramètres IOPS et de débit lors de l’ajout d’agrégats via la NetApp Console ou en utilisant l’ `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API.


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurations prises en charge pour Cloud Volumes ONTAP dans Google Cloud"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google documents : série de machines C3"^]



==== Déploiement simplifié de Cloud Volumes ONTAP dans Google Cloud

Vous pouvez désormais utiliser l'assistant *Quick create* pour déployer Cloud Volumes ONTAP sur Google Cloud, aussi bien pour les configurations à nœud unique que pour les configurations à haute disponibilité (paire haute disponibilité). Ce processus simplifié réduit le nombre d'étapes, définit automatiquement les valeurs par défaut sur une seule page et minimise la navigation pour un déploiement plus rapide et plus facile.

.Liens associés
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["Déployez Cloud Volumes ONTAP dans Google Cloud avec Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées dans Google Cloud"^]




==== Introduction des rôles d'accès pour Cloud Volumes ONTAP

NetApp introduit des rôles de gestion des identités et des accès (IAM) pour Cloud Volumes ONTAP, permettant le contrôle d'accès basé sur les rôles (RBAC) pour une meilleure sécurité et une conformité facilitée. Les utilisateurs peuvent continuer à se connecter à la NetApp Console en utilisant leurs identifiants existants pour les opérations Cloud Volumes ONTAP. Cependant, l'authentification est désormais acheminée via la fédération d'identités, ce qui permet à l'administrateur de la Console d'exercer un contrôle plus granulaire sur ces fonctions. Chaque utilisateur doit disposer de l'un des rôles suivants pour effectuer toute opération sur Cloud Volumes ONTAP. Sans rôle, les utilisateurs ne peuvent ni consulter ni accéder aux instances Cloud Volumes ONTAP.

* *Cloud Volumes ONTAP viewer* : Accorde un accès en lecture seule aux écrans et onglets de Cloud Volumes ONTAP. Certains écrans et boutons d’action sont désactivés dans ce rôle.
* *Cloud Volumes ONTAP operator* : Permet d’effectuer les tâches de gestion quotidiennes, telles que l’ajout de volumes, la gestion du stockage et la configuration de la réplication.
* *Administrateur Cloud Volumes ONTAP* : Fournit un accès complet à toutes les opérations Cloud Volumes ONTAP.


L'administrateur de la NetApp Console attribue des rôles aux utilisateurs Cloud Volumes ONTAP depuis *Administration > Identité*. Les autorisations de rôle sont basées sur l'organisation de l'utilisateur et s'appliquent à tous les systèmes Cloud Volumes ONTAP de cette organisation.

Cloud Volumes ONTAP applique le RBAC à l'aide d'un cache local des autorisations de chaque utilisateur, qui est actualisé automatiquement une fois par heure. Lorsqu'un utilisateur se voit attribuer un nouveau rôle ou que son rôle existant est modifié, la prise en compte de cette modification peut prendre jusqu'à une heure, après quoi tous les workflows autorisés par les rôles sont activés.


NOTE: Lors du premier déploiement d'un agent Console ou de la mise à niveau d'un agent Console existant vers Console 4.9.0 ou une version ultérieure, un processus d'initialisation unique attribue automatiquement les rôles Cloud Volumes ONTAP à tous les utilisateurs existants de l'organisation. Ce processus peut prendre jusqu'à 30 minutes pour être terminé. Une fois terminé, la Console attribue les rôles appropriés aux utilisateurs existants.

Les rôles Cloud Volumes ONTAP s'appliquent aux environnements Amazon Web Service (AWS), Microsoft Azure (Azure) et Google Cloud.

.Liens associés
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console rôles d'accès"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Rôles d'accès Cloud Volumes ONTAP dans la NetApp Console"^]




[[13-july-2026]]
== 13 juillet 2026



[[disaster-recovery]]
=== Reprise après sinistre



==== Mises à jour Kubernetes

La reprise après sinistre a introduit les modifications suivantes pour les charges de travail basées sur Kubernetes :



===== Gérez Trident Protect depuis le menu Sites

La solution de reprise après sinistre prend désormais en charge la gestion de Trident Protect directement depuis le menu Sites de l'interface utilisateur de la solution de reprise après sinistre. Vous pouvez mettre à niveau Trident Protect ou le supprimer de la solution de reprise après sinistre, ce qui simplifie la gestion de vos ressources Kubernetes.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Gérer les sites"^].



==== Mises à jour VMware

La reprise après sinistre a introduit les modifications suivantes pour les charges de travail basées sur VMware :



===== Basculement des datastores vides

Les plans de réplication incluant des banques de données vides peuvent désormais être basculés avec succès sans qu'il soit nécessaire de les exclure du plan ni de forcer le basculement. Lors du basculement, la reprise après sinistre monte automatiquement la banque de données vide sur le site de reprise après sinistre, permettant d'ajouter des machines virtuelles et de les protéger pour les opérations de retour arrière.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Basculement vers un site distant"^].



===== Mappage automatique des réseaux vCenter

Vous pouvez désormais configurer les relations de mappage réseau au niveau de vCenter (c’est-à-dire en dehors de la boîte de dialogue du plan de réplication). Une fois configuré, Disaster Recovery applique automatiquement ces mappages réseau lorsque vous ajoutez ou modifiez un plan de réplication, ce qui simplifie la gestion des plans de réplication.

La reprise après sinistre continue de prendre en charge les modifications par plan. Les mappages réseau existants définis dans un plan de réplication peuvent toujours être modifiés réseau par réseau ; ces mappages prévalent sur les définitions au niveau vCenter.



==== Restriction du rôle du spectateur en cas de reprise après sinistre

La possibilité de consulter l'onglet « Mise à niveau du système » a été supprimée du rôle de visionneur de reprise après sinistre. Cette modification aligne le rôle sur une expérience plus adaptée aux utilisateurs en lecture seule. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Découvrez les rôles et les autorisations des utilisateurs dans NetApp Disaster Recovery"^].



==== Améliorations des performances du système

La stratégie de reprise après sinistre a introduit des modifications visant à réduire la consommation des ressources système et à améliorer les performances opérationnelles.



[[07-july-2026]]
== 07 juillet 2026



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Exclure les chemins de fichiers des alertes de comportement utilisateur

Ransomware Resilience permet d'exclure certains chemins d'accès aux fichiers des alertes de surveillance du comportement des utilisateurs. Vous pouvez exclure des chemins d'accès si vous savez qu'ils ne sont pas à risque ou si vous effectuez des opérations sur des fichiers dans un volume susceptible de déclencher des alertes.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Exclure les chemins de fichiers des alertes"^].



==== Modèle ARM pour Microsoft Sentinel

Ransomware Resilience propose désormais un modèle Azure Resource Manager (ARM) pour la connexion à Microsoft Sentinel en tant que SIEM, offrant une méthode secondaire pour faciliter le déploiement.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Connectez-vous à un SIEM pour la détection et l'analyse des menaces"^].



[[29-june-2026]]
== 29 juin 2026



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Réponses automatisées aux alertes d'activité des utilisateurs

NetApp Ransomware Resilience prend désormais en charge l'automatisation de la création de snapshots et le blocage des utilisateurs lorsqu'une alerte d'activité utilisateur est générée. Avec des réponses automatisées, vous pouvez bloquer un utilisateur dès qu'un avertissement est généré et créer un snapshot pour la restauration, ce qui permet une réaction plus rapide sans intervention manuelle.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["Automatisez les réponses aux alertes d'activité des utilisateurs"^].



[[digital-advisor]]
=== Conseiller numérique



==== Améliorations de la migration GraphQL et de la précision des données pour le Health Check

Le module de vérification de l'état a été amélioré grâce à une meilleure précision des données et à des recommandations de version conformes aux normes de mise à jour. Dans le cadre de cette version, il a été migré de l'API publique vers GraphQL, offrant de meilleures performances, une flexibilité accrue dans les requêtes et un support à long terme.



===== Logiciels recommandés

Les améliorations logicielles recommandées dans le module Health Check fournissent désormais des données plus précises et cohérentes.

* Le nombre de baies et de disques affiché sous la version actuelle du firmware correspond aux valeurs précises par système et n'inclut plus le nombre de paires HA.
* Les recommandations de version minimale et de dernière version sont désormais calculées au niveau du cluster en fonction de la version effective du cluster, conformément aux normes en vigueur ; auparavant, ces recommandations étaient calculées au niveau du nœud.




===== AutoSupport dépendance des données

En raison des améliorations apportées au système, les vues d'adoption et de logiciels recommandés AutoSupport s'appuient sur les données AutoSupport les plus récentes. Cela pourrait affecter votre vue actuelle de la manière suivante :

[cols="30,70"]
|===
| Scénario | Systèmes affectés 


| Aucune donnée affichée | Systèmes n'ayant pas envoyé un AutoSupport depuis octobre 2025 


| Valeurs obsolètes | Les systèmes qui n'ont pas envoyé de AutoSupport au cours des 30 derniers jours 
|===
Redéclenchez AutoSupport sur les systèmes concernés listés ci-dessus pour restaurer les données actuelles dans les vues de contrôle d'intégrité.



[[keystone]]
=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Consultez la répartition des licences ADP pour les abonnements MetroCluster

Un nouveau sous-onglet *Distribution des licences* est désormais disponible dans l’onglet *Advanced data protection (ADP)*, vous offrant une visibilité sur l’utilisation des licences ADP au sein de vos clusters partenaires MetroCluster. Pour en savoir plus, consultez  https://docs.netapp.com/us-en/keystone-staas/integrations/adp-tab.html["Consultez la consommation et la santé de vos abonnements Keystone MetroCluster"].



==== Consultez l'état de la protection contre les ransomwares pour vos volumes

L'onglet *Volumes dans les clusters* de la section *Actifs* inclut désormais une colonne *État ARP* indiquant si la protection autonome contre les ransomwares (ARP) est activée ou désactivée pour chaque volume, vous offrant ainsi une visibilité sur votre niveau de protection contre les ransomwares sur l'ensemble des actifs gérés. Pour en savoir plus sur l'ARP, consultez https://docs.netapp.com/us-en/ontap/anti-ransomware/["Protection autonome contre les ransomwares (ARP) dans ONTAP"^].



==== Partagez vos commentaires à l'aide de l'onglet Feedback

Vous pouvez désormais donner votre avis depuis n'importe quel écran du tableau de bord Keystone grâce au nouvel onglet *Feedback*, ancré au bord inférieur droit de l'écran. En cliquant dessus, un panneau s'ouvre où vous pouvez partager votre expérience et soumettre des commentaires directement à NetApp.



==== Améliorez les alertes concernant l'utilisation des capacités et l'expiration des abonnements

Les moniteurs générés par le système fournissent désormais des alertes plus précises concernant l'utilisation des capacités et l'expiration des abonnements.

Pour l'expiration des abonnements, les alertes se déclenchent désormais à cinq seuils : 180, 90, 60, 30 et 7 jours avant l'expiration, la gravité augmentant d'informative à critique à mesure que la date approche.

Concernant l'utilisation de la capacité, le seuil d'alerte de saturation est désormais basé sur le pourcentage de saturation garanti de votre abonnement, et non plus sur un montant fixe de 20 %. Par exemple, si votre saturation garantie est de 40 %, l'alerte critique se déclenche à 140 % de l'utilisation de la capacité garantie.

Pour en savoir plus, consultez  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["Consultez et créez des moniteurs d'alerte pour les abonnements Keystone"].



[[15-june-2026]]
== 15 juin 2026



[[console-setup-and-administration]]
=== Configuration et administration de la console



==== Publication du mode privé (4.7.0)

Une nouvelle version en mode privé est désormais disponible au téléchargement depuis le https://mysupport.netapp.com/site/downloads["Site de support NetApp"^]

La version 4.7.0 inclut des mises à jour des composants et services suivants de la NetApp Console.

[cols="3*"]
|===
| Composant ou service | Version incluse dans cette release | Modifications depuis la version précédente du mode privé 


| Agent de console | 4.7.0 | Rendez-vous sur le  https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["Nouveautés de la page NetApp Console"^] et consultez les modifications incluses pour les versions 4.7.0. 


| NetApp Backup and Recovery | 5.4.0 (08 juin 2026) | Allez à la https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["Nouveautés de la page NetApp Backup and Recovery"^]. 


| NetApp Data Classification | 1.54.0 (11 mai 2026) | Allez à la https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["Nouveautés de la page Classification NetApp"^]. 
|===


[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.06* : Cette version inclut Trident Protect 26.06.
* *Ignorer la création d'applications lors de la restauration* : Vous pouvez désormais ignorer la création automatique d'objets de ressources personnalisés d'application lors des opérations de restauration. Cela réduit les entrées inutiles dans l’inventaire des applications.
* *Restauration des volumes persistants de machines virtuelles* : Lors de la restauration d’applications basées sur des machines virtuelles, vous pouvez désormais restaurer des volumes persistants individuels sans restaurer l’intégralité de la machine virtuelle, ce qui accélère la récupération lorsque des disques ou des volumes spécifiques sont affectés par une corruption ou une perte de données.
* *Améliorations du suivi des tâches* : Le suivi des tâches offre désormais une meilleure visibilité sur les tâches de protection Kubernetes. Vous pouvez consulter des informations d'état détaillées sur les tâches et sous-tâches, et voir le stockage cible utilisé par chacune.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



[[11-june-2026]]
== 11 juin 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Prise en charge d'une nouvelle région Azure dans Cloud Volumes ONTAP

Vous pouvez désormais déployer Cloud Volumes ONTAP 9.12.1 GA et versions ultérieures dans une ou plusieurs zones de disponibilité dans Azure dans la région Malaysia West (malaysiawest). Cela inclut la prise en charge des déploiements à nœud unique et à haute disponibilité (HA).

Pour obtenir la liste de toutes les régions, veuillez vous référer à  https://bluexp.netapp.com/cloud-volumes-global-regions["Carte des régions mondiales sous Azure"^].



[[08-june-2026]]
== 08 juin 2026



[[console-setup-and-administration]]
=== Configuration et administration de la console



==== Agent Console 4.8.0

La version 4.8.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité et des corrections de bugs.



==== Administration de la NetApp Console

Cette version inclut des améliorations de sécurité et des corrections de bugs.



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent l'amélioration suivante :

*Prise en charge du stockage cloud compatible S3* : NetApp Backup and Recovery pour les charges de travail Volumes prend désormais en charge la sauvegarde vers un stockage cloud compatible S3.

Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Améliorations concernant la restauration de fichiers et de dossiers sur une machine virtuelle invitée* : Vous pouvez désormais restaurer des fichiers et des dossiers à partir d’un instantané sur un stockage principal ou secondaire vers une machine virtuelle Windows invitée. Cette fonctionnalité est désormais prise en charge pour les VM CIFS et SAN.
* *Les groupes de protection utilisent désormais la planification du fuseau horaire de l'hôte* : Les groupes de protection utilisent désormais le fuseau horaire de l'hôte Hyper-V. Les groupes de protection créés avant l'introduction de la planification basée sur le fuseau horaire de l'hôte continuent d'utiliser leur heure précédemment configurée (généralement UTC). Pour mettre à jour ces groupes de protection afin qu'ils utilisent le fuseau horaire de l'hôte Hyper-V, vous devez recréer les planifications. Consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail Hyper-V"] pour plus d'informations.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Vue d'ensemble de la protection des charges de travail Hyper-V"].



==== Améliorations des charges de travail VMware

Dans cette version, les charges de travail VMware introduisent l'amélioration suivante :

* *Les groupes de protection utilisent désormais la planification selon le fuseau horaire de l’hôte* : les groupes de protection utilisent désormais le fuseau horaire du serveur VMware vCenter hôte. Les groupes de protection créés avant l’introduction de la planification selon le fuseau horaire de l’hôte continuent de fonctionner selon leur fuseau horaire précédemment configuré (généralement UTC). Pour utiliser le fuseau horaire de vCenter, vous devez recréer les planifications. Consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail VMware"] pour plus d’informations.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



[[data-classification]]
=== Classification des données



==== Améliorations générales

Cette version de Data Classification inclut des améliorations de sécurité et de performances.



[[disaster-recovery]]
=== Reprise après sinistre



==== Mises à jour Kubernetes

La reprise après sinistre a introduit les modifications suivantes pour les charges de travail basées sur Kubernetes :



===== Testez la prise en charge du basculement pour les charges de travail Kubernetes

La solution de reprise après sinistre prend désormais en charge le test du basculement pour les charges de travail Kubernetes. Le test du basculement vous permet de valider les plans de reprise après sinistre. Lorsque vous terminez le test, vous pouvez nettoyer le basculement de test afin que le système nettoie automatiquement les ressources de test pour réduire la charge et garantir la cohérence de votre environnement.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["Tester le processus de basculement"^].



===== Basculements de tests planifiés

Vous pouvez désormais automatiser les tests de reprise après sinistre en planifiant des basculements de test. Vous pouvez définir des calendriers de basculements de test récurrents afin de valider en continu les plans de reprise sans intervention manuelle, ce qui contribue à maintenir la confiance dans les objectifs de reprise et à respecter les exigences de conformité.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["Gérer les plans de réplication"^].



===== Découverte planifiée des charges de travail Kubernetes

Grâce à la découverte planifiée, vous pouvez contrôler la fréquence à laquelle Disaster Recovery recherche de nouvelles charges de travail Kubernetes. Vous pouvez configurer les intervalles de découverte pour les aligner avec votre cadence opérationnelle, réduisant la charge système inutile tout en garantissant que les nouvelles charges de travail sont détectées et protégées en temps opportun.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["Personnaliser le calendrier de découverte"^].



==== Mises à jour VMware



===== Protection des datastores vides

La solution de reprise après sinistre permet désormais de configurer la protection des banques de données ne contenant aucune machine virtuelle (VM). Toute VM ajoutée ultérieurement à la banque de données est automatiquement détectée par la solution de reprise après sinistre, moment auquel vous devrez fournir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["informations de mappage"^].

Lorsque vous ajoutez une banque de données vide à un plan de protection, vous devez soit la supprimer du plan de protection avant d'effectuer un basculement, soit effectuer un basculement forcé. Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Basculement vers un site distant"^].



===== Réintégrer les banques de données précédemment exclues dans un plan de protection

Les banques de données précédemment exclues de la protection peuvent désormais y être réintégrées. Cette amélioration offre une plus grande flexibilité lors de la gestion et de la mise à jour de vos configurations de reprise après sinistre au fil du temps.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Gérer les sites, les groupes de ressources et les plans de réplication"^].



===== Basculement plus rapide pour les banques de données basées sur VMFS

La reprise après sinistre a amélioré les performances de basculement des banques de données VMFS. Les opérations de réanalyse de l'adaptateur de bus hôte (HBA) et de montage de la banque de données sont désormais exécutées en parallèle, ce qui réduit les temps de basculement globaux et minimise l'interruption pendant les opérations de récupération.

Pour plus d'informations sur les basculements, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Basculement avec reprise après sinistre"^].



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Flexibilité accrue pour les stratégies de protection

La solution Ransomware Resilience offre désormais une plus grande flexibilité dans le choix des stratégies de détection des ransomwares. Auparavant, toutes les stratégies de protection contre les ransomwares devaient inclure la détection du chiffrement. Désormais, vous pouvez activer une stratégie de protection contre les ransomwares basée uniquement sur la détection du comportement de l'utilisateur.

Les stratégies de protection peuvent toujours inclure la détection du chiffrement  la détection des comportements suspects des utilisateurs. Le blocage des extensions de fichiers peut également être ajouté à toute stratégie de protection.

Si vous désactivez une partie de la stratégie de protection d'une politique existante, les alertes créées dans le cadre de la version précédente de cette politique ne peuvent être marquées que comme « Résolues » et non comme « Ignorées ». Par exemple, si vous aviez une stratégie de protection qui incluait la détection du chiffrement et le comportement utilisateur suspect, mais que vous avez désactivé la détection du chiffrement, vous ne pouvez résoudre qu'une alerte de chiffrement existante pour cette charge de travail.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Protégez les charges de travail avec les stratégies de protection NetApp Ransomware Resilience"^].



==== Améliorations apportées au playbook SOAR

Les playbooks SOAR de Ransomware Resilience proposent désormais des étapes de remédiation après que vous avez bloqué un utilisateur ou mis un volume hors ligne. Vous pouvez désormais remettre un volume en ligne et débloquer un utilisateur si l'action a été jugée non constitutive d'une menace de type ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer un playbook SOAR"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Prise en charge des nouvelles instances EC2 pour Cloud Volumes ONTAP dans AWS

Cloud Volumes ONTAP 9.16.1 et versions ultérieures prennent en charge les familles d'instances EC2 M6id et M6idn pour les déploiements à nœud unique et à haute disponibilité (HA) sur AWS, qu'ils soient nouveaux ou existants. Ces instances de 6e génération offrent une puissance de traitement plus rapide, des capacités réseau renforcées et des performances supérieures aux systèmes à usage général de 5e génération.

* Instances M6id : Elles offrent un équilibre entre puissance de calcul et mémoire grâce à un stockage NVMe local haute vitesse et faible latence. Toutes les tailles d’instances M6id prennent en charge Flash Cache. Ces instances sont parfaitement adaptées aux charges de travail telles que l’enregistrement de données et le traitement multimédia.
* *Instances M6idn* : Offrent les mêmes capacités de stockage NVMe local que les instances M6id. Toutes les tailles d’instances M6idn prennent en charge Flash Cache.


Nous déconseillons les instances de petite taille m6id.xlarge, m6id.2xlarge, m6idn.xlarge et m6idn.2xlarge pour les charges de travail exigeantes en termes de performances ou de mémoire. Pour ces charges de travail, privilégiez une instance dotée d'un nombre de cœurs plus élevé et d'une mémoire plus importante.

Pour plus d'informations, consultez  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configurations prises en charge pour Cloud Volumes ONTAP dans AWS"^].



[[03-june-2026]]
== 03 juin 2026



[[lifecycle-planning]]
=== Planification du cycle de vie



==== Mises à jour du nom de la fonctionnalité de planification du cycle de vie

Les fonctionnalités de planification du cycle de vie suivantes ont vu leur nom modifié :

* La fonction de mise à jour technique s'appelle désormais *Actualisation du système*. Découvrez comment https://docs.netapp.com/us-en/console-lifecycle-planning/use/tech-refresh.html["évaluer une mise à jour du système"].
* La fonctionnalité d'ajout de capacité s'appelle désormais *Storage Expansion*. Découvrez comment https://docs.netapp.com/us-en/console-lifecycle-planning/use/capacity-add.html["étendre le stockage"].
* La fonctionnalité Renouvellements s'appelle désormais *Renouvellements d'assistance*. Découvrez comment https://docs.netapp.com/us-en/console-lifecycle-planning/support/task-support-registration.html["s'inscrire pour obtenir de l'aide"].




[[digital-advisor]]
=== Conseiller numérique



==== Mises à jour du nom du widget Digital Advisor

Les fonctionnalités suivantes de Digital Advisor ont changé de nom :

* La fonction « Actualisation technique » s’appelle désormais « Actualisation du système ». Découvrez comment link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["évaluer une mise à jour du système"].
* La fonctionnalité « Ajout de capacité » s’appelle désormais « Extension de stockage ». En savoir plus link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets Digital Advisor"].
* La fonctionnalité Renouvellements s'appelle désormais Renouvellements d'assistance. En savoir plus link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets Digital Advisor"].




[[26-may-2026]]
== 26 mai 2026



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Prise en charge de Google Cloud NetApp Volumes (aperçu)

Ransomware Resilience prend désormais en charge la création de groupes de protection pour les charges de travail dans les systèmes Google Cloud NetApp Volumes, ce qui vous permet d’organiser plusieurs charges de travail sous une seule stratégie afin de simplifier la gestion.

Pour plus d’informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Créer un groupe de protection dans Ransomware Resilience"^].



[[25-may-2026]]
== 25 mai 2026



[[keystone]]
=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Affichage amélioré des mises à jour multiples effectuées le même jour dans la chronologie de l'abonnement

Le graphique de l'historique des abonnements affiche désormais un chiffre lorsque plusieurs mises à jour d'abonnements de types différents ont lieu le même jour, au lieu d'icônes distinctes. Survolez le chiffre pour afficher tous les types de mises à jour de ce jour-là. Le rapport téléchargé comprend une ligne distincte pour chaque mise à jour, vous offrant ainsi un historique complet de toutes les modifications. Pour en savoir plus, consultez  https://docs.netapp.com/us-en/keystone-staas/integrations/subscription-timeline.html["Consultez la chronologie de vos abonnements Keystone"].



[[18-may-2026]]
== 18 mai 2026



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Prise en charge de Google Cloud NetApp Volumes (aperçu)

Ransomware Resilience prend désormais en charge les systèmes Google Cloud NetApp Volumes, vous permettant de détecter et de contrer efficacement les menaces de ransomware dans Google Cloud NetApp Volumes. Lorsque vous effectuez une découverte, Ransomware Resilience affiche automatiquement les charges de travail provenant des systèmes Google Cloud NetApp Volumes. Lorsque vous découvrez les systèmes, ils apparaissent dans le tableau de bord de Ransomware Resilience. La prise en charge de Google Cloud NetApp Volumes dans Ransomware Resilience est actuellement en préversion.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Découvrez la résilience face aux ransomwares"^]. Pour des informations sur l'étendue de la prise en charge de Google Cloud NetApp Volumes, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Limites de la résilience face aux ransomwares"^].



==== Améliorations de la restauration propre

La restauration complète prend désormais en charge les rapports. Grâce aux rapports, vous pouvez consulter et évaluer les restaurations complètes, en enregistrant ces informations hors ligne au format CSV.

La restauration propre permet désormais d'interrompre l'analyse. Si vous interrompez l'analyse, vous devez recommencer la restauration propre.

Pour en savoir plus sur les rapports, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Télécharger les rapports dans Ransomware Resilience"^]. Pour en savoir plus sur la récupération, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Déploiement simplifié de Cloud Volumes ONTAP dans Azure

Vous pouvez désormais utiliser la création rapide pour déployer Cloud Volumes ONTAP dans Azure, aussi bien pour les configurations à nœud unique que pour les configurations à haute disponibilité (HA). Ce processus simplifié réduit le nombre d'étapes par rapport à la méthode avancée, définit automatiquement les valeurs par défaut sur une seule page et minimise la navigation, rendant le déploiement plus rapide et plus facile.

.Liens associés
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Déployez Cloud Volumes ONTAP dans Azure avec Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées dans Azure"^]




[[digital-advisor]]
=== Conseiller numérique



==== Revue de bien-être

À compter de juillet 2026, la fonctionnalité « Bilan bien-être » ne sera plus disponible dans Digital Advisor. Pour toute question, veuillez envoyer un courriel à mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].



[[12-may-2026]]
== 12 mai 2026



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Facturation flexible pour Cloud Volumes ONTAP et les services de données dans AWS

NetApp propose des options de facturation améliorées pour vos abonnements Cloud Volumes ONTAP dans AWS, vous offrant un meilleur contrôle sur la façon dont vous payez la capacité Cloud Volumes ONTAP et les services de données NetApp, tels que NetApp Backup and Recovery. Auparavant, toute l’utilisation de Cloud Volumes ONTAP et des services de données était facturée ensemble via l’offre NetApp Intelligent Services (NIS) sur la place de marché AWS.

Suite aux modifications apportées au programme de remises pour entreprises AWS (EDP), NetApp a introduit un abonnement Cloud Volumes ONTAP autonome sur la place de marché AWS qui vous permet de dissocier la facturation de la capacité Cloud Volumes ONTAP de celle des services de données. Cette dissociation vous offre une plus grande flexibilité dans la gestion de vos crédits et coûts EDP. NetApp recommande d'utiliser l'abonnement autonome pour une meilleure gestion des coûts liés à votre utilisation de Cloud Volumes ONTAP, tout en continuant d'utiliser l'abonnement NIS pour la facturation des services de données après le 31 juillet 2026, lorsque les exigences EDP entreront en vigueur.

L'abonnement Cloud Volumes ONTAP autonome sur AWS prend uniquement en charge les packages de licence Essentials ou Freemium valides, basés sur la capacité. Le package Professional n'est pas pris en charge. Vous pouvez choisir le mode de facturation qui correspond le mieux à vos besoins :

* *Abonnement Cloud Volumes ONTAP autonome (recommandé)* : payez votre utilisation de Cloud Volumes ONTAP via l’abonnement autonome sur la place de marché AWS, tout en continuant à facturer les services de données via l’abonnement NIS. C’est l’option recommandée pour la plupart des clients qui disposent à la fois d’un abonnement autonome et d’un abonnement NIS associés à leur compte AWS dans la NetApp Console.
* *Abonnement NIS combiné* : payez à la fois Cloud Volumes ONTAP et les services de données ensemble via l'inscription NIS existante. La formule combinée sera valable pour les clients existants qui ont uniquement des abonnements NIS associés à leur compte AWS dans la NetApp Console. Cependant, NetApp recommande de définir vos préférences de facturation pour votre utilisation de Cloud Volumes ONTAP et de passer à l'abonnement autonome pour une meilleure gestion des coûts.


Selon votre type d'abonnement, vous bénéficiez des scénarios suivants :

.Abonnement autonome uniquement (nouveaux clients)
Si vous ne disposez que d'un abonnement AWS autonome associé à votre compte AWS dans la NetApp Console et d'aucun abonnement NIS, vous ne pouvez sélectionner que le pack de licences Essentials lors du déploiement. L'option de service de données *Backup and Recovery* ne vous est pas disponible.

.Abonnements autonomes et NIS (clients existants)
Si votre compte AWS comprend à la fois un abonnement NIS et un abonnement autonome, et que vous n'avez pas défini de préférence de facturation dans l'onglet *Préférences de facturation* de la NetApp Console, l'utilisation de Cloud Volumes ONTAP continue d'être facturée par défaut via NIS. Ceci est également le comportement par défaut pour toute instance Cloud Volumes ONTAP exécutant le package Professional, car l'offre autonome ne prend pas en charge Professional. Vous pouvez définir une préférence de facturation et choisir le mode de facturation de chaque service :

* Configurez l'abonnement autonome comme compte de facturation préféré pour Cloud Volumes ONTAP (avec le package Essentials). Si vous ne possédez que le package Professional, vous pouvez le convertir en package Essentials et facturer votre utilisation de Cloud Volumes ONTAP en définissant la préférence de facturation. Nous recommandons cette méthode car elle vous permet de gérer vos crédits EDP Cloud Volumes ONTAP plus efficacement.
* Utilisez l'abonnement NIS pour la facturation des services de données ou l'utilisation de Cloud Volumes ONTAP via le pack Professionnel. Lors du déploiement, activez le service de données *Backup and Recovery* et sélectionnez le pack de licences Professionnel pour facturer les services de données via l'abonnement NIS.


.Abonnement NIS uniquement (clients existants)
Ceci s'applique si vous êtes déjà client et disposez d'abonnements NIS associés à votre compte AWS. Vous pouvez continuer à facturer Cloud Volumes ONTAP et les services de données ensemble comme actuellement. Cependant, NetApp recommande de passer à l'approche d'abonnement autonome pour une meilleure gestion des coûts de votre utilisation de Cloud Volumes ONTAP :

* Abonnez-vous à une nouvelle fiche produit autonome sur le portail AWS.
* Associez l'abonnement autonome à votre compte AWS.
* Définissez votre préférence de facturation sur l’abonnement autonome pour l’utilisation de Cloud Volumes ONTAP avec le forfait Essentials.
* (Le cas échéant) Convertissez votre forfait Professional en forfait Essentials et définissez votre préférence de facturation.
* Continuez à facturer les services de données via votre abonnement NIS.



NOTE: Aucun comptage en double ne se produit lorsque vous utilisez plusieurs types d'abonnement ou que vous migrez entre des annonces.

.Lien associé
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["Configurer les licences pour Cloud Volumes ONTAP dans AWS"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["Modifier les méthodes de facturation des licences de capacité"^]




[[11-may-2026]]
== 11 mai 2026



[[console-setup-and-administration]]
=== Configuration et administration de la console



==== Agent Console 4.7.0

La version 4.7.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité et des corrections de bugs.



==== Administration de la NetApp Console

Cette version inclut la fonctionnalité suivante.

.Vérifiez l'organisation de votre Console
Par défaut, Digital Advisor affiche tous les comptes NetApp associés à votre entreprise, plutôt qu'à votre seule organisation Console. Pour limiter l'affichage dans Digital Advisor à un compte spécifique, vérifiez le compte professionnel que vous souhaitez utiliser avec votre organisation Console. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["Découvrez comment vérifier votre organisation Console"^]



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Protection des machines virtuelles sur stockage SAN* : Vous pouvez désormais protéger les machines virtuelles sur le stockage objet SAN.
* *Améliorations de la restauration vers un emplacement alternatif* : Vous pouvez désormais restaurer vers un emplacement alternatif à partir des emplacements principal et secondaire pour les machines virtuelles sur un stockage SAN.
* *Restaurez des fichiers et des dossiers sur une machine virtuelle invitée* : Vous pouvez désormais restaurer des fichiers et des dossiers à partir d’un instantané du stockage principal vers une machine virtuelle Windows invitée. Cette fonctionnalité est prise en charge uniquement pour les machines virtuelles CIFS.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Vue d'ensemble de la protection des charges de travail Hyper-V"].



==== Améliorations des charges de travail KVM

Cette version introduit l'amélioration suivante pour les charges de travail KVM :

*Restauration vers un autre emplacement* : Vous pouvez désormais restaurer les machines virtuelles KVM vers un autre emplacement (cette fonctionnalité est désormais disponible en disponibilité générale).

Pour plus de détails sur la protection des charges de travail KVM, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Présentation de la protection des charges de travail KVM"] .



==== Améliorations des charges de travail Oracle Database

Cette version introduit les améliorations suivantes pour les charges de travail de la base de données Oracle :

* *Prise en charge d'Oracle AI Database 26ai* : NetApp Backup and Recovery prend désormais en charge Oracle AI Database 26ai.
* *Prise en charge de la vérification des sauvegardes* : Vous pouvez désormais configurer des stratégies de sauvegarde pour vérifier automatiquement l’intégrité de vos sauvegardes de base de données Oracle.


Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Vue d'ensemble de la protection des workloads Oracle Database"].



==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

* *Prise en charge des datastores répartis pour les groupes de protection* : Vous pouvez désormais choisir le comportement des groupes de protection lors de la protection de machines virtuelles dont les disques virtuels s’étendent sur plusieurs datastores.
* *Prise en charge du clonage* : Vous pouvez désormais créer des clones d’instantanés de machines virtuelles à partir du stockage principal et secondaire.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.05.1*: Cette version inclut Trident Protect 26.05.1.
* *Restauration sur place pour les applications basées sur des machines virtuelles* : Vous pouvez désormais restaurer les applications basées sur des machines virtuelles dans l’espace de noms et le cluster d’origine.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



[[data-classification]]
=== Classification des données



==== Page de configuration améliorée

La page de configuration de Data Classification a été mise à jour et améliorée, offrant ainsi une expérience utilisateur optimisée pour la gestion des paramètres, des systèmes, l'activation des analyses et la surveillance de l'état du système. La nouvelle page de configuration propose la fonctionnalité existante dans un format plus intuitif, avec en plus la possibilité de filtrer les systèmes par type, état d'erreur et état d'analyse. La nouvelle page fournit également un récapitulatif des systèmes connectés et un aperçu des analyses actives et configurées.

Examinez un link:https://youtu.be/_8YJ3KyZ7nI["visite vidéo"^]. Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Analyser les sources de données avec la classification des données"^].



==== Rôle d'administrateur de conformité IAM

La classification des données prend désormais en charge un rôle d'administrateur de conformité permettant de gérer les autorisations dans Data Classification. Le rôle d'administrateur de conformité n'a pas accès aux ressources, y compris les agents Console et les espaces de travail. Les utilisateurs disposant du rôle d'administrateur de conformité doivent être associés à au moins un autre rôle.

Lors de l'installation de Data Classification, vous devez disposer d'un rôle d'administrateur de la plateforme Console ou du rôle d'administrateur de conformité.

Si vous êtes déjà utilisateur, votre accès devrait continuer normalement. Par exemple, un rôle de plateforme qui possède un rôle d'administrateur de dossier ou de projet dispose d'un accès existant.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Rôles de la classification des données"^].



==== Déployez la classification des données avec OVA

NetApp Data Classification prend désormais en charge le déploiement avec VMware Open Virtual Appliance (OVA), offrant une stratégie de déploiement simplifiée pour les environnements VMware vSphere sur site.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Déployez la classification des données avec OVA"^].



[[disaster-recovery]]
=== Reprise après sinistre



==== Prise en charge des charges de travail basées sur Kubernetes (aperçu)

NetApp Disaster Recovery inclut désormais la prise en charge des charges de travail basées sur Kubernetes. Avec la prise en charge de Kubernetes, vous pouvez protéger les applications exécutées sur des clusters Kubernetes, y compris les environnements de virtualisation OpenShift. Disaster Recovery prend en charge link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["toute version de Kubernetes actuellement prise en charge par Trident Protect"^], assurant une intégration transparente et des capacités de reprise après sinistre robustes pour les applications conteneurisées.

Principales caractéristiques de la prise en charge des charges de travail basées sur Kubernetes :

* **Large compatibilité** : La reprise après sinistre prend en charge toutes les versions de Kubernetes compatibles avec Trident Protect, y compris Red Hat OpenShift Virtualization.
* **Protection centrée sur l'application** : Vous pouvez désormais protéger les charges de travail Kubernetes au niveau de l'application, garantissant ainsi la reprise des services critiques lors des basculements.
* **Orchestration simplifiée** : La reprise après sinistre offre des flux de travail intuitifs pour automatiser la sauvegarde et la réplication des charges de travail Kubernetes, en tirant parti de la même technologie efficace SnapMirror utilisée pour les environnements VMware.


La prise en charge des charges de travail basées sur Kubernetes est actuellement en préversion. Pour commencer à protéger les charges de travail basées sur Kubernetes, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Exigences de Kubernetes pour NetApp Disaster Recovery"^].



[[ransomware-resilience]]
=== Résilience aux ransomwares



==== Améliorations de la restauration propre

La restauration propre prend désormais en charge la récupération vers un emplacement alternatif, ce qui vous permet de restaurer des volumes sur différents systèmes, machines virtuelles de stockage et agrégats gérés par le même agent Console. De plus, la restauration propre a supprimé la limitation de sept jours dans la recherche de snapshots exploitables pour la récupération. La restauration propre continue désormais de rechercher un point de récupération viable parmi les snapshots disponibles, quelle que soit la distance par rapport à l'événement de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].



==== Assistance Google SecOps SIEM

Ransomware Resilience prend désormais en charge la gestion des informations et des événements de sécurité (SIEM) avec Google SecOps, vous permettant d'envoyer automatiquement des données à Google SecOps pour une analyse et une détection des menaces simplifiées.

Pour plus d'informations sur la configuration, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Connectez NetApp Ransomware Resilience à un SIEM"^].



==== La prise en charge d'Azure NetApp Files est désormais disponible pour tous

Ransomware Resilience prend désormais en charge les systèmes Azure NetApp Files, vous permettant de détecter et de contrer efficacement les menaces de ransomware dans Azure NetApp Files. Lors de la découverte des charges de travail, Ransomware Resilience présente désormais Azure NetApp Files et les affiche dans le tableau de bord de protection. La prise en charge d’Azure NetApp Files par Ransomware Resilience inclut des stratégies de détection et de protection uniquement avec des instantanés. La prise en charge d’Azure NetApp Files est désormais généralement disponible (GA).

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Découvrez la résilience face aux ransomwares"^].



==== Prise en charge SOAR pour le blocage des utilisateurs

Ransomware Resilience prend désormais en charge le blocage individuel des utilisateurs avec Google SecOps et les playbooks SOAR de Splunk. Avec cette addition, vous pouvez automatiser le blocage des utilisateurs lorsque Ransomware Resilience détecte une activité utilisateur suspecte, telle qu'une violation de données ou une suppression massive de données.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer un playbook SOAR"^].



[[05-may-2026]]
== 5 mai 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.05* : Cette version inclut Trident Protect 26.05.
* *Mise à niveau de Trident Protect depuis Backup and Recovery* : Si votre cluster Kubernetes exécute Trident Protect 26.05 ou une version plus récente, vous pouvez désormais mettre à niveau Trident Protect directement depuis Backup and Recovery.
* *Prise en charge native de la protection des machines virtuelles* : Vous pouvez désormais créer des applications basées sur des machines virtuelles, ce qui vous permet de protéger ces dernières de la même manière que n’importe quelle autre application.
* *Transformations des ressources* : Vous pouvez désormais utiliser des transformations de ressources et des modèles de transformation de ressources pour ajouter, supprimer et modifier les attributs des ressources pendant le processus de restauration.
* *Afficher les ressources protégées* : Vous pouvez désormais consulter les ressources incluses dans chaque point de récupération d’une application et télécharger un rapport JSON détaillé. Vous bénéficiez ainsi d’une visibilité complète sur vos points de récupération et simplifiez la conformité aux audits.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



[[27-april-2026]]
== 27 avril 2026



[[keystone]]
=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Étiquette de capacité provisionnée renommée

L'intitulé *Capacité provisionnée* est renommé *Capacité volumique provisionnée*. Le nouvel intitulé est également reflété dans les rapports CSV et Excel associés.



==== Basculement des prévisions pour la rafale accumulée

Vous pouvez désormais utiliser le bouton *Prévisions* dans la vue *Consommation cumulée des pics* de l’onglet *Tendance de consommation* pour projeter la consommation cumulée des pics pour les 120 prochains jours à compter de la date actuelle. Pour en savoir plus, consultez  https://docs.netapp.com/us-en/keystone-staas/integrations/consumption-tab.html#view-forecast-data["Consulter les données prévisionnelles"].



[[20-april-2026]]
== 20 avril 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail VMware

Dans cette version, les charges de travail VMware introduisent l'amélioration suivante :

*ASA r2 prise en charge SAN* : Les charges de travail VMware prennent désormais en charge la protection des machines virtuelles sur des banques de données VMFS hébergées par des environnements NetApp ASA r2 SAN uniquement.

Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].
