---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.



== Services obsolètes



=== Mise en cache de périphérie

Le service de mise en cache de périphérie a été supprimé le 7 août 2024.



=== Kubernetes

La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



=== Rapports de migration

Le service de rapports de migration a été supprimé le 7 août 2024.



=== Résilience opérationnelle

Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.



=== Assainissement

Le service de remédiation a été supprimé le 22 avril 2024.



== 09 février 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version des charges de travail Kubernetes introduit les fonctionnalités améliorées suivantes :

* *Prise en charge du flux de travail CR* : Vous pouvez désormais effectuer des tâches de protection courantes à l’aide des CR ainsi que de l’interface utilisateur Web Backup and Recovery.
* *Migration de clusters* : Vous pouvez désormais ajouter des clusters Kubernetes existants protégés par Trident Protect à Backup and Recovery.
* *Prise en charge du framework d'alertes* : Vous pouvez désormais recevoir des alertes par e-mail et via l'interface utilisateur pour certains événements de charge de travail Kubernetes.
* *Intégration de l'onglet Restauration* : Vous pouvez désormais accéder aux actions de restauration de charge de travail Kubernetes depuis le menu Restauration.
* *Prise en charge de l'architecture de sauvegarde 3-2-1 fanout* : Vous pouvez désormais utiliser une architecture 3-2-1 fanout dans votre politique de protection lors de la protection des charges de travail Kubernetes.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



==== Améliorations des charges de travail Oracle Database

Cette version des charges de travail Oracle Database introduit les fonctionnalités améliorées suivantes :

* *Prise en charge des utilisateurs non root* : Les utilisateurs non root peuvent désormais effectuer des opérations de sauvegarde, de restauration et de clonage, améliorant la sécurité et la conformité.
* *Prise en charge du clonage* : Les fonctionnalités de clonage sont désormais prises en charge dans les environnements NAS, SAN et ASM principaux et secondaires en utilisant ASM library v2, permettant des flux de travail de protection coordonnés.
* *Prise en charge du fractionnement des clones* : Vous pouvez désormais fractionner les instantanés inscriptibles (clones) de leurs volumes parents, libérer de l’espace de stockage et permettre des opérations indépendantes.
* *Sauvegarde et restauration pour le stockage d'objets* : Les fonctionnalités natives de sauvegarde et de restauration sont désormais prises en charge pour les cibles de stockage S3 compatibles basées sur des objets.
* *Gestion du cycle de vie des clones (CLM)*: Les opérations d’actualisation des clones sont prises en charge sur le stockage principal.
* *Clonage vers un hôte alternatif* : Vous pouvez désormais cloner des bases de données vers un hôte différent (pour des tests ou de l’analytique) à partir du stockage principal et secondaire.
* *Prise en charge des groupes de cohérence ONTAP* : Les groupes de cohérence ONTAP sont désormais pris en charge, garantissant des instantanés cohérents au niveau des applications sur plusieurs volumes.
* Backup and Recovery prend désormais en charge les architectures de stratégie de protection suivantes pour les charges de travail Oracle Database :
+
** Fanout 3-2-1
** Disque à disque
** Du disque au stockage objet
** En cascade
** Instantané local




Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Vue d'ensemble de la protection des workloads Oracle Database"].



==== Autres améliorations

Les charges de travail Hyper-V, les charges de travail KVM et les charges de travail VMware sont désormais généralement disponibles (GA) dans NetApp Backup and Recovery.



=== Classification des données



==== Version 1.50

Cette version de Data Classification inclut des correctifs de bogues et les mises à jour suivantes :

.Activez la classification des données avec Amazon FSxN pour ONTAP directement depuis le canevas NetApp Console
Vous pouvez désormais activer Amazon FSxN pour ONTAP directement depuis le canevas NetApp Console, ce qui vous permet de lancer plus rapidement la classification des données pour vos systèmes FSxN.

Pour plus d'informations sur l'utilisation de la classification des données avec Amazon FSxN pour ONTAP, consultez link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-fsx.html["Analyser les volumes Amazon FSxN pour ONTAP"^].

.Augmentation du plafond d'exportation pour l'investigation des répertoires
Lors de l'exportation d'un rapport d'enquête sur les répertoires depuis le tableau de bord Enquête, vous pouvez désormais inclure 10 000 lignes. Cette augmentation par rapport à la limite précédente de 5 000 lignes prend en charge des enquêtes à plus grande échelle sur la gouvernance des données et la conformité.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Examiner les données"^].

.Limite accrue pour la copie et le déplacement
Lors de la copie ou du déplacement de fichiers, vous pouvez désormais déplacer des fichiers jusqu'à 250 Mo, une augmentation par rapport à la limite précédente de 50 Mo.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Examiner les données"^].

.Affichage amélioré pour les écrans basse résolution
Data Classification a amélioré ses performances d'affichage sur les écrans basse résolution, améliorant l'expérience utilisateur.



=== Cloud Volumes ONTAP



==== Prise en charge de Google Cloud Infrastructure Manager

Cloud Volumes ONTAP 9.16.1 et versions ultérieures prennent désormais en charge  https://docs.cloud.google.com/infrastructure-manager/docs/overview["Google Cloud Infrastructure Manager"^] (IM) au lieu de  https://docs.cloud.google.com/deployment-manager/docs/deprecations["Gestionnaire de déploiement cloud"^] (DM) pour les nouveaux déploiements sur Google Cloud. Google va déprécier Deployment Manager en tant que service d'infrastructure dans un avenir proche au profit d'Infrastructure Manager, plus avancé.

Désormais, déployez automatiquement Cloud Volumes ONTAP pour utiliser Infrastructure Manager ou basculez vos déploiements existants dans Deployment Manager vers Infrastructure Manager en exécutant un outil de conversion. La conversion est un processus unique, après quoi vos systèmes commenceront automatiquement à utiliser Infrastructure Manager. Consultez  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-gcp-dm-im-conv.html["Configurer les déploiements Cloud Volumes ONTAP existants pour Google Cloud Infrastructure Manager"^] pour obtenir des instructions sur l'exécution de l'outil de transition.

Les systèmes Cloud Volumes ONTAP qui utilisent Infrastructure Manager utilisent des buckets Google Cloud Storage pour stocker les données et les enregistrements dans la zone du premier déploiement afin de conserver les enregistrements de déploiement, qui sont réutilisés pour les déploiements suivants. Des frais supplémentaires peuvent s’appliquer pour ces compartiments, mais ne modifiez pas et ne supprimez pas les compartiments ni leur contenu :

* `gs://netapp-cvo-infrastructure-manager-<project id>/dm-to-im-convert` : pour stocker les fichiers Terraform de Cloud Volumes ONTAP
* `<gcp project number>-<region>-blueprint-config`: pour stocker les artefacts Terraform de Google Cloud


.Liens associés
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-gcp.html["Premiers pas avec Cloud Volumes ONTAP dans Google Cloud"^]
* https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#console-agent-4-2-0["NetApp Console Agent 4.2.0 Notes de version"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Autorisations requises pour Google Cloud Infrastructure Manager"^]




== 04 février 2026



=== Conseiller numérique



==== Nouveau rapport de sécurité pour une supervision complète de la sécurité

Digital Advisor inclut désormais un rapport de sécurité offrant une vue unifiée des risques de sécurité ONTAP au sein de votre environnement de stockage. Ce rapport permet une détection plus rapide des erreurs de configuration, des lacunes de conformité et des problèmes de sécurité sur les clusters, les SVM et les volumes, vous aidant à maintenir une infrastructure de stockage sécurisée.



==== Prise en charge améliorée de Upgrade Advisor pour les niveaux de correctifs mixtes

Upgrade Advisor génère désormais des rapports de mise à niveau pour les clusters dont les nœuds exécutent différents niveaux de correctifs au sein d'une même version majeure d'ONTAP. Cette amélioration garantit que les clients peuvent procéder aux mises à niveau sans interruption tant que le cluster n'est pas composé de versions majeures mixtes, offrant ainsi une plus grande flexibilité dans la planification des mises à niveau.



==== Prise en charge étendue pour les versions ONTAP en fin de support limité

Upgrade Advisor prend désormais en charge la génération de plans de mise à niveau pour les versions ONTAP ayant atteint la fin du support limité, avec un délai de grâce de 9 mois. Cette fonctionnalité aide les clients à agir rapidement et à éviter les interruptions de mise à niveau en leur fournissant des instructions claires pendant la période de transition.



== 02 février 2026



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Filtrage interactif des données de pointe quotidiennes accumulées

Le tableau « Frais cumulés par jour » de l’onglet « Tendance de consommation » prend désormais en charge le filtrage interactif. Sélectionnez une barre du graphique de facturation des frais cumulés pour afficher uniquement les jours de cette période de facturation. Pour en savoir plus, consultez link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Afficher l’utilisation quotidienne des données en rafale"].



==== Affichage amélioré de la plage de dates dans le graphique des rafales cumulées

Le graphique de facturation cumulée dans l’onglet *Tendance de consommation* affiche désormais des plages de dates complètes pour chaque période de facturation, telles que du 01 oct. 2025 au 31 oct. 2025, au lieu du mois et de l’année seulement.



==== Vue détaillée extensible de l'abonnement

L'onglet *Abonnements* propose une option permettant de développer tous les abonnements et d'afficher simultanément les informations relatives aux niveaux de performance de chaque abonnement. Pour en savoir plus, consultez link:./integrations/subscriptions-tab.html["Consultez les détails de vos abonnements Keystone"].



==== Nouvelle colonne Usage type

L'onglet *Abonnements* comprend une colonne *Type d'utilisation* qui indique si l'abonnement est facturé en fonction de l'utilisation provisionnée, physique ou logique. Pour en savoir plus, consultez link:./integrations/subscriptions-tab.html["Consultez les détails de vos abonnements Keystone"].



== 19 janvier 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail volumiques ONTAP

Cette version des charges de travail de volume ONTAP introduit la fonctionnalité améliorée suivante :

*Prise en charge de plusieurs compartiments* : (Aperçu privé) À partir d’ ONTAP 9.17.1 et versions ultérieures, vous pouvez désormais protéger les volumes d’un système avec jusqu’à 6 compartiments par système sur différents fournisseurs de cloud.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["Découvrez comment sauvegarder les données de volume ONTAP à l'aide de NetApp Backup and Recovery."].



==== Améliorations des charges de travail VMware

Cette version des charges de travail VMware introduit les fonctionnalités améliorées suivantes :

* La prise en charge des charges de travail VMware est désormais disponible en disponibilité générale (GA) dans NetApp Backup and Recovery.
* Vous pouvez désormais restaurer les fichiers et dossiers du système d'exploitation invité.


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["Apprenez-en davantage sur la restauration des fichiers et dossiers invités."].



==== Améliorations de la préversion des charges de travail Hyper-V

Cette version des charges de travail Hyper-V introduit les fonctionnalités améliorées suivantes :

* Vous pouvez désormais restaurer les sauvegardes et les instantanés de machines virtuelles Hyper-V vers un autre emplacement. Utilisez cette fonctionnalité pour gérer les versions de machines virtuelles sur différents hôtes Hyper-V.
* NetApp Backup and Recovery prend désormais en charge les machines virtuelles Hyper-V provisionnées par System Center Virtual Machine Manager (SCVMM) et hébergées sur un partage CIFS.
* Vous pouvez désormais modifier les groupes de protection.



NOTE: Dans cette version uniquement, vous ne pouvez pas mettre à niveau les plugins NetApp pour Hyper-V ou Windows à l'aide de l'option *Mettre à niveau* du menu Actions. Il faut plutôt supprimer chaque hôte Hyper-V et l'ajouter à nouveau pour mettre à jour les plugins.

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["Découvrez comment restaurer des machines virtuelles Hyper-V avec NetApp Backup and Recovery."].



==== Améliorations de la prévisualisation des charges de travail KVM

La préversion des charges de travail KVM protège désormais les hôtes KVM et les machines virtuelles qui sont gérées par Apache CloudStack.

Pour plus de détails sur la protection des charges de travail KVM, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Présentation de la protection des charges de travail KVM"] .



=== Résilience aux ransomwares



==== Volumes non pris en charge

Les rapports de résilience aux ransomwares capturent désormais des informations sur les volumes pris en charge et non pris en charge dans le rapport **Résumé**. Utilisez ces informations pour diagnostiquer pourquoi certains volumes d'un système pourraient ne pas être éligibles à la protection contre les ransomwares.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Télécharger les rapports dans Ransomware Resilience"^].



== 14 janvier 2026



=== Classification des données



==== Version 1.50

Cette version de Data Classification inclut des correctifs de bogues et les mises à jour suivantes :

.Améliorations de la classification personnalisée
La classification des données prend désormais en charge la création de catégories personnalisées pour vos données. Vous pouvez télécharger des fichiers pour affiner un modèle d'IA que la classification des données utilise pour appliquer le marqueur de catégorie aux données. L'interface de toutes les classifications personnalisées a été améliorée.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Créer une classification personnalisée"^].

.Définition de données obsolètes personnalisée
La classification des données vous permet désormais de personnaliser la définition des données obsolètes afin qu'elle corresponde aux besoins de votre organisation. Auparavant, les données obsolètes étaient définies comme toutes les données dont la dernière modification remontait à trois ans. Désormais, les données obsolètes peuvent être identifiées en fonction de leur dernière consultation ou de leur dernière modification ; cette période peut aller de 6 mois à 10 ans.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["Personnaliser la définition des données obsolètes"^].

.Performances améliorées
Les temps de chargement de toutes les pages de la section Classification des données, du rapport de cartographie des données et des filtres de la page Investigation ont été réduits.

.Délai estimé pour les rapports d'enquête
Lorsque vous téléchargez un rapport d'enquête, la classification des données affiche désormais le temps estimé pour la fin du téléchargement.



== 12 janvier 2026



=== Configuration et administration de la console



==== Agent de console 4.3.0

La version 4.3.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité, des corrections de bugs et les fonctionnalités suivantes :

.Capacité à valider les connexions réseau des agents de la console
Vous pouvez désormais valider les connexions réseau des agents Console connectés directement depuis la NetApp Console. Cette fonctionnalité permet de vérifier la connectivité et de résoudre les problèmes avec les agents Console. Ceci s'ajoute à la possibilité existante d'exécuter des diagnostics réseau depuis la ligne de commandes de la console de maintenance de l'agent Console (CLI).

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Apprenez à exécuter la configuration depuis la NetApp Console."]



==== Administration de la NetApp Console

Cette version comprend les éléments suivants :

.Contrôle d'accès basé sur les rôles pour les groupes fédérés dans la NetApp Console
La NetApp Console prend en charge l'attribution de rôles aux groupes fédérés (par exemple, les groupes Active Directory), permettant aux administrateurs d'automatiser l'intégration et la désintégration des utilisateurs en fonction de leur appartenance à un groupe dans le fournisseur d'identité (IdP) de l'organisation. Cette fonctionnalité réduit la charge administrative et garantit un accès sécurisé et cohérent en mettant à jour instantanément l'accès à la console lorsque les appartenances aux groupes changent.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["Découvrez comment donner accès à un groupe fédéré à votre organisation."]

.Prise en charge de la fédération lorsque la NetApp Console est en mode restreint
Vous pouvez désormais activer la fédération pour une organisation NetApp Console en mode restreint. Cela permet aux utilisateurs de se connecter à la console en utilisant leurs identifiants d'entreprise tout en conservant les avantages de sécurité du mode restreint.

.Mode lecture seule
Vous pouvez configurer une organisation NetApp Console en mode lecture seule. En mode lecture seule, les utilisateurs peuvent consulter les ressources et les paramètres, mais ne peuvent apporter aucune modification. Un administrateur ou un super administrateur d'organisation peut activer le mode lecture seule pour une organisation. Lorsque le mode lecture seule est activé, les utilisateurs disposant de rôles d'administrateur doivent élever manuellement leurs autorisations pour effectuer les modifications nécessaires.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Découvrez comment activer le mode lecture seule pour une organisation Console."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["Découvrez comment rehausser votre rôle lorsque votre organisation est en mode lecture seule."]



=== Reprise après sinistre



==== Prise en charge de plusieurs agents de console dans les environnements sur site

Si vous utilisez la reprise après sinistre sur site, vous pouvez désormais déployer un agent Console pour chaque instance vCenter, ce qui améliore la résilience.

Par exemple, si vous avez deux sites (sites A et B), le site A peut avoir l'agent de console A attaché à vCenter 1, au déploiement ONTAP 1 et au déploiement ONTAP 2. Le site B peut avoir l'agent de console B attaché aux déploiements vCenter 2 et ONTAP 3 et 4.

Pour plus d'informations sur l'agent Console dans le cadre de la reprise après sinistre, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["Créer l'agent de console"^].



==== Ajoutez des machines virtuelles après le basculement pour les plans de réplication utilisant la protection basée sur le datastore.

En cas de basculement, tout plan de réplication utilisant une protection basée sur la banque de données inclut les machines virtuelles ajoutées à la banque de données, à condition qu'elles aient été découvertes. Vous devez fournir les détails de mappage des machines virtuelles ajoutées avant que le basculement ne soit terminé.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Applications de basculement"^].



==== Nouvelles notifications par e-mail

Le service de reprise après sinistre envoie désormais des notifications par e-mail pour les événements suivants :

* Limite d'utilisation de la capacité proche
* Génération du rapport terminée
* échecs professionnels
* Expiration ou infractions au permis




==== Améliorations de Swagger

Vous pouvez désormais accéder à la documentation Swagger directement depuis le système de reprise après sinistre. Dans la section Reprise après sinistre, sélectionnez **Paramètres** puis **Documentation API** pour accéder à Swagger, ou consultez cette URL en mode navigation privée/incognito de votre navigateur : link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^].



==== Interfaces utilisateur améliorées

La solution de reprise après sinistre offre désormais des avertissements et des résolutions d'erreurs améliorés. Cette version corrige une erreur qui empêchait l'affichage des tâches annulées dans l'interface utilisateur. Les tâches annulées sont désormais visibles. Un nouvel avertissement s'affiche également lorsque le même réseau de destination est associé à plusieurs réseaux sources différents.



==== Conserver la structure de dossiers des machines virtuelles ajoutée par défaut dans les plans de réplication

Lors de la création d'une réplication, le comportement par défaut consiste désormais à conserver la structure des dossiers de la machine virtuelle. Si le répertoire cible de récupération ne possède pas l'arborescence de dossiers d'origine, la fonction de récupération après sinistre la crée. Vous pouvez désélectionner cette option pour ignorer l'arborescence des dossiers d'origine.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"^].



=== Résilience aux ransomwares



==== Répliquer les instantanés sur ONTAP

Ransomware Resilience prend désormais en charge l'ajout de la réplication des instantanés vers un site ONTAP secondaire. Avec les groupes de protection qui utilisent une stratégie de réplication, vous pouvez répliquer vers la même destination ou vers des destinations différentes pour chaque charge de travail. Vous pouvez créer une stratégie de protection contre les ransomwares incluant la réplication ou utiliser la stratégie prédéfinie.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Protéger les charges de travail grâce à la résilience contre les ransomwares"^].



==== Exclure les charges de travail de la résilience aux ransomwares

Ransomware Resilience prend désormais en charge l'exclusion de certaines charges de travail d'un système de la protection et du tableau de bord Ransomware Resilience. Vous pouvez exclure les charges de travail après leur découverte, puis les réinclure si vous souhaitez ajouter une protection contre les ransomwares. Les charges de travail exclues ne vous seront pas facturées.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads["Exclure les charges de travail"^].



==== Les alertes marquées comme étant en cours de révision

Ransomware Resilience vous permet désormais de marquer les alertes comme « En cours d'examen ». Utilisez l'étiquette « En cours d'examen » pour améliorer la clarté au sein de votre équipe lors du tri et de la gestion des menaces de ransomware actives.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gérer les alertes dans Ransomware Resilience"^].



=== Cloud Volumes ONTAP



==== Option de facturation privilégiée pour Cloud Volumes ONTAP

Vous pouvez désormais sélectionner l'option de facturation qui vous convient le mieux pour calculer votre consommation et vos dépassements Cloud Volumes ONTAP . Étant donné la disponibilité limitée du modèle de licence Bring Your Own Licenses (BYOL) le 25 juin 2025, NetApp a ajouté des méthodes de facturation préférées dans la section *Licences et abonnements* de la NetApp Console. Vous pouvez utiliser soit votre abonnement annuel à la plateforme pour la facturation et les dépassements, soit le modèle BYOL existant comme option privilégiée. Cela vous permet de choisir la méthode de facturation qui correspond le mieux à la stratégie financière et aux habitudes d'utilisation de votre organisation.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#billing-preferences-and-overages["Préférences de facturation et dépassements"^].



== 10 décembre 2025



=== Configuration et administration de la console



==== Agent de console 4.2.0

La version 4.2.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité, des corrections de bugs et les fonctionnalités suivantes :

.Prise en charge de Google Cloud Infrastructure Manager
NetApp utilise désormais Google Cloud Infrastructure Manager (IM) au lieu de Google Cloud Deployment Manager pour déployer et gérer les agents dans Google Cloud. Ce changement a été effectué car Google va déprécier link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Gestionnaire de déploiement cloud"].

* Tous les nouveaux agents 4.2.0 et supérieurs utilisent Infrastructure Manager et vous devez mettre à jour les autorisations du compte utilisateur et du compte de service utilisés pour le déploiement. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Consultez le journal des modifications d'autorisation."^]
* Lors du déploiement d'un agent, le système crée également un bucket Google Cloud pour stocker les fichiers de déploiement.


.Amélioration des contrôles de configuration pour les agents de console
* L'agent de la console vérifie désormais la présence de points de terminaison obsolètes lors de l'exécution d'une vérification de configuration. Si vous n'avez pas mis à jour la liste des points de terminaison pour la version 4.0.0 ou supérieure, les installations réussissent si le système peut atteindre la liste des points de terminaison précédente. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Apprenez-en davantage sur les points de terminaison requis pour les agents de la console."^]
* Effectuez des vérifications de configuration sur les agents de console installés depuis la console ou la console de maintenance des agents afin de vérifier la connectivité et de résoudre les problèmes. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Apprenez comment effectuer des vérifications de configuration sur les agents de la console."^]


.Téléchargez directement le logiciel agent depuis la NetApp Console.
Lorsque vous devez installer manuellement un agent, vous pouvez accéder au logiciel de l'agent directement depuis la NetApp Console , en plus du site de support NetApp . link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Découvrez comment télécharger le logiciel agent de la console directement depuis la NetApp Console."^]



==== Administration de la NetApp Console

Cette version comprend les éléments suivants :

.Possibilité de configurer des notifications pour les identifiants expirant
Configurez les notifications d'expiration des identifiants sur les comptes de service et les fédérations. Choisissez entre sept ou 30 jours. La console affiche des notifications et envoie des e-mails aux utilisateurs ayant le rôle approprié. Les administrateurs de l'organisation reçoivent des notifications relatives aux comptes de service. Les administrateurs d'organisation, les administrateurs de fédération et les utilisateurs de la fédération reçoivent des notifications de fédération.

.Les connexions locales ne sont plus disponibles après l'activation de la fédération.
Une fois la fédération activée pour une organisation Console, les utilisateurs ne peuvent plus utiliser les identifiants locaux et sont redirigés vers les identifiants de fédération.

.Améliorations de l'ergonomie des pages de gestion du stockage
Les informations détaillées concernant vos systèmes ONTAP sur site (et FSx pour ONTAP) sont désormais plus faciles à consulter et à gérer à partir des pages de gestion du stockage.

* La page * Discoverable systems* sépare les informations récapitulatives de l'affichage par onglets des systèmes disponibles, facilitant ainsi la consultation d'informations complètes sur les systèmes détectables.




=== Clusters ONTAP sur site



==== Améliorations de l'ergonomie lors de la visualisation des systèmes ONTAP depuis la NetApp Console (mode standard uniquement)

La page *Systèmes* de la NetApp Console a été améliorée pour une meilleure clarté et une utilisation plus conviviale lors de la gestion des volumes et des clusters. Ces mises à jour permettent d'harmoniser davantage l'expérience avec System Manager pour les versions ONTAP plus récentes et simplifient la navigation.

.Capacité de cluster incluse pour les versions ONTAP 9.5 et supérieures (mode standard Console uniquement)
La page *Systèmes > Vue d'ensemble* affiche la taille du cluster ainsi que la version ONTAP pour les clusters exécutant ONTAP 9.5 et versions ultérieures.

Pour NetApp Console en mode restreint ou les versions ONTAP 9.5 et inférieures, les informations de provisionnement du volume restent inchangées.

.L'onglet Volumes de la page Systèmes affiche par défaut l'affichage en grille si vous avez plus de 20 clusters ONTAP locaux.
Lorsque vous gérez plus de 20 clusters ONTAP sur site dans la NetApp Console, l'onglet *Volume* passe par défaut en mode grille pour une navigation plus facile. L'affichage par carte est désactivé.

Cette modification s'applique uniquement au mode standard et aux versions ONTAP 9.6 et supérieures.



== 9 décembre 2025



=== Reprise après sinistre



==== conservation de la hiérarchie des dossiers

Par défaut, la reprise après sinistre conserve la hiérarchie d'inventaire des machines virtuelles (structure des dossiers) lors d'un basculement. Si le dossier requis n'est pas présent sur la cible de récupération, la fonction de récupération après sinistre le crée.

Vous pouvez désormais modifier ce paramètre en désignant un nouveau dossier parent pour la machine virtuelle ou en décochant l'option **Conserver la hiérarchie de dossiers d'origine**.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Créer un plan de réplication"].



==== Mise à jour simplifiée de l'agent de console

La reprise après sinistre prend désormais en charge un processus simplifié pour l'utilisation de plusieurs agents Console dans un environnement de travail. Pour changer d'agent de console, vous devez modifier la configuration de votre vCenter, redécouvrir les informations d'identification et actualiser les plans de réplication pour utiliser le nouvel agent de console.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["Agents de la console de commutation"].



== 8 décembre 2025



=== Sauvegarde et récupération



==== Améliorations en avant-première des charges de travail VMware

La version préliminaire des charges de travail VMware introduit les fonctionnalités améliorées suivantes :

* Vous pouvez désormais restaurer les sauvegardes et les instantanés vers un autre emplacement. Ceci est utile si vous souhaitez gérer des versions d'une machine virtuelle sur différents déploiements VMware vCenter, hôtes VMware ESXi ou banques de données VMware.


link:br-use-vmware-restore.html["Découvrez comment restaurer des machines virtuelles VMware avec NetApp Backup and Recovery."].

* Vous pouvez désormais restaurer des disques virtuels VMware spécifiques (images VMDK) à partir d'un emplacement principal ou secondaire, ce qui permet un contrôle plus précis de la restauration des données de la machine virtuelle.


link:br-use-vmware-restore-vmdks-from-backups.html["Découvrez comment restaurer les disques virtuels VMware avec NetApp Backup and Recovery."].



=== Classification des données



==== Version 1.49

Cette version de Data Classification inclut des correctifs de bogues et les mises à jour suivantes :

.Surveillez les indicateurs et les performances dans le tableau de bord de surveillance de la santé.
Data Classification propose désormais un tableau de bord de surveillance de l'état de santé, offrant une surveillance en temps réel de vos ressources et des informations sur l'utilisation de la mémoire, l'utilisation du disque, le taux d'utilisation du disque, et plus encore. Grâce aux informations fournies par le tableau de bord de surveillance de l'état de santé, vous pouvez examiner l'infrastructure de votre déploiement et obtenir des informations permettant d'optimiser le stockage et les performances.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Surveiller l'état de la classification des données"].

.Performances de chargement améliorées
Les performances de chargement de toutes les pages de la section Classification des données ont été améliorées afin d'offrir une expérience utilisateur plus efficace.



=== Résilience aux ransomwares



==== Le blocage des extensions est activé au niveau de la charge de travail.

Lorsque vous activez le blocage des extensions, celui-ci est désormais activé au niveau de la charge de travail et non plus au niveau de la machine virtuelle de stockage.



==== Modifier l'état d'alerte du comportement de l'utilisateur

Ransomware Resilience vous permet désormais de modifier le statut des alertes comportementales des utilisateurs. Vous pouvez ignorer et résoudre manuellement les alertes.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gérer les alertes dans Ransomware Resilience"^].



==== Prise en charge de plusieurs agents de console

Ransomware Resilience prend désormais en charge l'utilisation de plusieurs agents Console pour gérer les mêmes systèmes.

Pour plus d'informations sur les agents de console, consultezlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Créer un agent de console"] .



=== Cloud Volumes ONTAP



==== Possibilité d'améliorer les performances des disques SSD Premium v2 dans Azure

Vous pouvez désormais améliorer les performances des disques gérés Premium SSD v2 dans Azure en modifiant les paramètres IOPS et de débit. Grâce à cette fonctionnalité, vous pouvez optimiser les performances de stockage de vos systèmes en fonction des exigences de votre charge de travail.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Gérer les performances des disques SSD Premium v2 pour Cloud Volumes ONTAP dans Azure"^].



==== La facturation des dépassements pour les licences Essentials a été simplifiée.

Pour les contrats annuels/offres privées du marché Cloud Volumes ONTAP , les calculs de dépassement pour les licences Essentials sont désormais alignés sur les forfaits Bring Your Own License (BYOL). Auparavant, les dépassements étaient facturés aux tarifs horaires du marché pour le forfait Essentiels exact. Désormais, si votre contrat annuel sur le marché comprend plusieurs forfaits Essentials, la NetApp Console facture les dépassements d'un forfait Essentials en fonction de la capacité disponible d'un forfait Essentials plus cher dans votre abonnement. Cela simplifie les calculs de dépassement pour les forfaits Essentials et assure une transition en douceur du modèle de licence BYOL vers un modèle par abonnement.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Comment les dépassements sont facturés pour les licences Essentials"^]



==== Prise en charge des séries de tailles Azure Edsv6

À partir de Cloud Volumes ONTAP 9.17.1, vous pouvez déployer des machines virtuelles Azure Edsv6 via la NetApp Console pour les nouvelles instances Cloud Volumes ONTAP . Cloud Volumes ONTAP 9.17.1 et versions ultérieures ne prendront en charge que les machines virtuelles de génération 2 pour les nouveaux déploiements. Ces machines de deuxième génération sont compatibles avec les technologies les plus récentes, telles que l'interface de microprogramme extensible unifiée (UEFI), les systèmes Azure Boost et NVMe. Ils sont idéaux pour les systèmes et applications gourmands en mémoire qui nécessitent un stockage local rapide, tels que les serveurs de bases de données et les moteurs d'analyse.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configurations prises en charge pour Cloud Volumes ONTAP dans Azure"^]



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Étiquette renommée « Capacité de rupture accumulée »

L'étiquette *Capacité de pointe cumulée* est renommée *Capacité de pointe cumulée*.



== 1er décembre 2025



=== Reprise après sinistre



==== Prise en charge de Google Cloud VMware Engine à l'aide de Google Cloud NetApp Volumes

NetApp Disaster Recovery prend désormais en charge Google Cloud VMware Engine utilisant Google Cloud NetApp Volumes pour les opérations de migration, de basculement, de restauration et de test. Cette intégration permet des flux de travail de reprise après sinistre transparents entre les environnements sur site et Google Cloud.

Assurez-vous de consulter lelink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["prérequis"] etlink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["limites"] pour Google Cloud.



== 27 novembre 2025



=== Google Cloud NetApp Volumes



==== Modifications des identifiants Google Cloud Platform

À mesure que les clients configurent et autorisent davantage de systèmes Google Cloud NetApp Volumes , la gestion des identifiants a évolué.

Les informations d'identification des systèmes NetApp Volumes sont désormais stockées sur un serveur cloud Google, tel que le service Cloud Key Management ou un service similaire, et les informations d'identification d'emprunt d'identité du compte de service sont utilisées lors de la création d'un nouveau système.



== 24 novembre 2025



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Identifiant de suivi pour les abonnements avec interruption de couverture

Dans la boîte de notification *Complétez votre couverture* de *Surveillance > Moniteurs d'alerte*, chaque abonnement affiche désormais son identifiant de suivi à côté du numéro d'abonnement.



== 17 novembre 2025



=== Amazon FSX pour ONTAP



==== Gestionnaire système disponible lors de l'utilisation d'un lien AWS Lambda

L'interface ONTAP System Manager peut être utilisée avec une liaison AWS Lambda pour effectuer des opérations ONTAP avancées. Cela offre une alternative à l'utilisation d'un agent Console avec System Manager pour gérer un système de fichiers FSx for ONTAP directement depuis la console. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Découvrez comment utiliser les liens pour les opérations ONTAP avancées."^]
