---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.



== Services obsolètes



=== Mise en cache de périphérie

Le service de mise en cache de périphérie a été supprimé le 7 août 2024.



=== Kubernetes

La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



=== Rapports de migration

Le service de rapports de migration a été supprimé le 7 août 2024.



=== Résilience opérationnelle

Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.



=== Assainissement

Le service de remédiation a été supprimé le 22 avril 2024.



== 10 décembre 2025



=== Configuration et administration de la console



==== Agent de console 4.2.0

La version 4.2.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité, des corrections de bugs et les fonctionnalités suivantes :

.Prise en charge de Google Cloud Infrastructure Manager
NetApp utilise désormais Google Cloud Infrastructure Manager (IM) au lieu de Google Cloud Deployment Manager pour déployer et gérer les agents dans Google Cloud. Ce changement a été effectué car Google va déprécier link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Gestionnaire de déploiement cloud"].

* Tous les nouveaux agents 4.2.0 et supérieurs utilisent Infrastructure Manager et vous devez mettre à jour les autorisations du compte utilisateur et du compte de service utilisés pour le déploiement. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Consultez le journal des modifications d'autorisation."^]
* Lors du déploiement d'un agent, le système crée également un bucket Google Cloud pour stocker les fichiers de déploiement.


.Amélioration des contrôles de configuration pour les agents de console
* L'agent de la console vérifie désormais la présence de points de terminaison obsolètes lors de l'exécution d'une vérification de configuration. Si vous n'avez pas mis à jour la liste des points de terminaison pour la version 4.0.0 ou supérieure, les installations réussissent si le système peut atteindre la liste des points de terminaison précédente. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Apprenez-en davantage sur les points de terminaison requis pour les agents de la console."^]
* Effectuez des vérifications de configuration sur les agents de console installés depuis la console ou la console de maintenance des agents afin de vérifier la connectivité et de résoudre les problèmes. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Apprenez comment effectuer des vérifications de configuration sur les agents de la console."^]


.Téléchargez directement le logiciel agent depuis la NetApp Console.
Lorsque vous devez installer manuellement un agent, vous pouvez accéder au logiciel de l'agent directement depuis la NetApp Console , en plus du site de support NetApp . link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Découvrez comment télécharger le logiciel agent de la console directement depuis la NetApp Console."^]



==== Administration de la NetApp Console

Cette version comprend les éléments suivants :

.Possibilité de configurer des notifications pour les identifiants expirant
Configurez les notifications d'expiration des identifiants sur les comptes de service et les fédérations. Choisissez entre sept ou 30 jours. La console affiche des notifications et envoie des e-mails aux utilisateurs ayant le rôle approprié. Les administrateurs de l'organisation reçoivent des notifications relatives aux comptes de service. Les administrateurs d'organisation, les administrateurs de fédération et les utilisateurs de la fédération reçoivent des notifications de fédération.

.Les connexions locales ne sont plus disponibles après l'activation de la fédération.
Une fois la fédération activée pour une organisation Console, les utilisateurs ne peuvent plus utiliser les identifiants locaux et sont redirigés vers les identifiants de fédération.

.Améliorations de l'ergonomie des pages de gestion du stockage
Les informations détaillées concernant vos systèmes ONTAP sur site (et FSx pour ONTAP) sont désormais plus faciles à consulter et à gérer à partir des pages de gestion du stockage.

* La page * Discoverable systems* sépare les informations récapitulatives de l'affichage par onglets des systèmes disponibles, facilitant ainsi la consultation d'informations complètes sur les systèmes détectables.




=== Clusters ONTAP sur site



==== Améliorations de l'ergonomie lors de la visualisation des systèmes ONTAP depuis la NetApp Console (mode standard uniquement)

La page *Systèmes* de la NetApp Console a été améliorée pour une meilleure clarté et une utilisation plus conviviale lors de la gestion des volumes et des clusters. Ces mises à jour permettent d'harmoniser davantage l'expérience avec System Manager pour les versions ONTAP plus récentes et simplifient la navigation.

.Capacité de cluster incluse pour les versions ONTAP 9.5 et supérieures (mode standard Console uniquement)
La page *Systèmes > Vue d'ensemble* affiche la taille du cluster ainsi que la version ONTAP pour les clusters exécutant ONTAP 9.5 et versions ultérieures.

Pour NetApp Console en mode restreint ou les versions ONTAP 9.5 et inférieures, les informations de provisionnement du volume restent inchangées.

.L'onglet Volumes de la page Systèmes affiche par défaut l'affichage en grille si vous avez plus de 20 clusters ONTAP locaux.
Lorsque vous gérez plus de 20 clusters ONTAP sur site dans la NetApp Console, l'onglet *Volume* passe par défaut en mode grille pour une navigation plus facile. L'affichage par carte est désactivé.

Cette modification s'applique uniquement au mode standard et aux versions ONTAP 9.6 et supérieures.



== 9 décembre 2025



=== Reprise après sinistre



==== conservation de la hiérarchie des dossiers

Par défaut, la reprise après sinistre conserve la hiérarchie d'inventaire des machines virtuelles (structure des dossiers) lors d'un basculement. Si le dossier requis n'est pas présent sur la cible de récupération, la fonction de récupération après sinistre le crée.

Vous pouvez désormais modifier ce paramètre en désignant un nouveau dossier parent pour la machine virtuelle ou en décochant l'option **Conserver la hiérarchie de dossiers d'origine**.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.adoc["Créer un plan de réplication"].



==== Mise à jour simplifiée de l'agent de console

La reprise après sinistre prend désormais en charge un processus simplifié pour l'utilisation de plusieurs agents Console dans un environnement de travail. Pour changer d'agent de console, vous devez modifier la configuration de votre vCenter, redécouvrir les informations d'identification et actualiser les plans de réplication pour utiliser le nouvel agent de console.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agents.html["Agents de la console de commutation"].



== 8 décembre 2025



=== Sauvegarde et récupération



==== Améliorations en avant-première des charges de travail VMware

La version préliminaire des charges de travail VMware introduit les fonctionnalités améliorées suivantes :

* Vous pouvez désormais restaurer les sauvegardes et les instantanés vers un autre emplacement. Ceci est utile si vous souhaitez gérer des versions d'une machine virtuelle sur différents déploiements VMware vCenter, hôtes VMware ESXi ou banques de données VMware.


link:br-use-vmware-restore.html["Découvrez comment restaurer des machines virtuelles VMware avec NetApp Backup and Recovery."].

* Vous pouvez désormais restaurer des disques virtuels VMware spécifiques (images VMDK) à partir d'un emplacement principal ou secondaire, ce qui permet un contrôle plus précis de la restauration des données de la machine virtuelle.


link:br-use-vmware-restore-vmdks-from-backups.html["Découvrez comment restaurer les disques virtuels VMware avec NetApp Backup and Recovery."].



=== Classification des données



==== Version 1.49

Cette version de Data Classification inclut des correctifs de bogues et les mises à jour suivantes :

.Surveillez les indicateurs et les performances dans le tableau de bord de surveillance de la santé.
Data Classification propose désormais un tableau de bord de surveillance de l'état de santé, offrant une surveillance en temps réel de vos ressources et des informations sur l'utilisation de la mémoire, l'utilisation du disque, le taux d'utilisation du disque, et plus encore. Grâce aux informations fournies par le tableau de bord de surveillance de l'état de santé, vous pouvez examiner l'infrastructure de votre déploiement et obtenir des informations permettant d'optimiser le stockage et les performances.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Surveiller l'état de la classification des données"].

.Performances de chargement améliorées
Les performances de chargement de toutes les pages de la section Classification des données ont été améliorées afin d'offrir une expérience utilisateur plus efficace.



=== Résilience aux ransomwares



==== Le blocage des extensions est activé au niveau de la charge de travail.

Lorsque vous activez le blocage des extensions, celui-ci est désormais activé au niveau de la charge de travail et non plus au niveau de la machine virtuelle de stockage.



==== Modifier l'état d'alerte du comportement de l'utilisateur

Ransomware Resilience vous permet désormais de modifier le statut des alertes comportementales des utilisateurs. Vous pouvez ignorer et résoudre manuellement les alertes.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gérer les alertes dans Ransomware Resilience"^].



==== Prise en charge de plusieurs agents de console

Ransomware Resilience prend désormais en charge l'utilisation de plusieurs agents Console pour gérer les mêmes systèmes.

Pour plus d'informations sur les agents de console, consultezlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Créer un agent de console"] .



=== Cloud Volumes ONTAP



==== Possibilité d'améliorer les performances des disques SSD Premium v2 dans Azure

Vous pouvez désormais améliorer les performances des disques gérés Premium SSD v2 dans Azure en modifiant les paramètres IOPS et de débit. Grâce à cette fonctionnalité, vous pouvez optimiser les performances de stockage de vos systèmes en fonction des exigences de votre charge de travail.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Gérer les performances des disques SSD Premium v2 pour Cloud Volumes ONTAP dans Azure"^].



==== La facturation des dépassements pour les licences Essentials a été simplifiée.

Pour les contrats annuels/offres privées du marché Cloud Volumes ONTAP , les calculs de dépassement pour les licences Essentials sont désormais alignés sur les forfaits Bring Your Own License (BYOL). Auparavant, les dépassements étaient facturés aux tarifs horaires du marché pour le forfait Essentiels exact. Désormais, si votre contrat annuel sur le marché comprend plusieurs forfaits Essentials, la NetApp Console facture les dépassements d'un forfait Essentials en fonction de la capacité disponible d'un forfait Essentials plus cher dans votre abonnement. Cela simplifie les calculs de dépassement pour les forfaits Essentials et assure une transition en douceur du modèle de licence BYOL vers un modèle par abonnement.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Comment les dépassements sont facturés pour les licences Essentials"^]



==== Prise en charge des séries de tailles Azure Edsv6

À partir de Cloud Volumes ONTAP 9.17.1, vous pouvez déployer des machines virtuelles Azure Edsv6 via la NetApp Console pour les nouvelles instances Cloud Volumes ONTAP . Cloud Volumes ONTAP 9.17.1 et versions ultérieures ne prendront en charge que les machines virtuelles de génération 2 pour les nouveaux déploiements. Ces machines de deuxième génération sont compatibles avec les technologies les plus récentes, telles que l'interface de microprogramme extensible unifiée (UEFI), les systèmes Azure Boost et NVMe. Ils sont idéaux pour les systèmes et applications gourmands en mémoire qui nécessitent un stockage local rapide, tels que les serveurs de bases de données et les moteurs d'analyse.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configurations prises en charge pour Cloud Volumes ONTAP dans Azure"^]



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Étiquette renommée « Capacité de rupture accumulée »

L'étiquette *Capacité de pointe cumulée* est renommée *Capacité de pointe cumulée*.



== 1er décembre 2025



=== Reprise après sinistre



==== Prise en charge de Google Cloud VMware Engine à l'aide de Google Cloud NetApp Volumes

NetApp Disaster Recovery prend désormais en charge Google Cloud VMware Engine utilisant Google Cloud NetApp Volumes pour les opérations de migration, de basculement, de restauration et de test. Cette intégration permet des flux de travail de reprise après sinistre transparents entre les environnements sur site et Google Cloud.

Assurez-vous de consulter lelink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["prérequis"] etlink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["limites"] pour Google Cloud.



== 27 novembre 2025



=== Google Cloud NetApp Volumes



==== Modifications des identifiants Google Cloud Platform

À mesure que les clients configurent et autorisent davantage de systèmes Google Cloud NetApp Volumes , la gestion des identifiants a évolué.

Les informations d'identification des systèmes NetApp Volumes sont désormais stockées sur un serveur cloud Google, tel que le service Cloud Key Management ou un service similaire, et les informations d'identification d'emprunt d'identité du compte de service sont utilisées lors de la création d'un nouveau système.



== 24 novembre 2025



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Identifiant de suivi pour les abonnements avec interruption de couverture

Dans la boîte de notification *Complétez votre couverture* de *Surveillance > Moniteurs d'alerte*, chaque abonnement affiche désormais son identifiant de suivi à côté du numéro d'abonnement.



== 17 novembre 2025



=== Amazon FSX pour ONTAP



==== Gestionnaire système disponible lors de l'utilisation d'un lien AWS Lambda

L'interface ONTAP System Manager peut être utilisée avec une liaison AWS Lambda pour effectuer des opérations ONTAP avancées. Cela offre une alternative à l'utilisation d'un agent Console avec System Manager pour gérer un système de fichiers FSx for ONTAP directement depuis la console. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Découvrez comment utiliser les liens pour les opérations ONTAP avancées."^]



== 11 novembre 2025



=== Cloud Volumes ONTAP



==== Option de facturation privilégiée pour Cloud Volumes ONTAP

Vous pouvez désormais choisir votre option de facturation préférée pour le calcul de votre consommation et de vos dépassements. Suite à la disponibilité restreinte des licences BYOL à compter du 25 juin 2025, NetApp propose des méthodes de facturation privilégiées dans la section *Licences et abonnements* de la NetApp Console. Vous pouvez utiliser soit votre abonnement annuel au marché pour la facturation et les dépassements, soit le modèle de licence existant (BYOL). Cela vous offre la flexibilité de choisir la méthode de facturation qui correspond le mieux à la stratégie financière et aux habitudes d'utilisation de votre organisation.

Pour plus d'informations, veuillez consulter https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#minimum-charge["Facturation et dépassements"^] .



=== Amazon FSX pour ONTAP



==== Prise en charge de la réplication entre les systèmes ONTAP sur site et les systèmes de fichiers FSx pour ONTAP

La réplication des données est disponible entre un système ONTAP sur site et un système de fichiers FSx pour ONTAP depuis la page Systèmes de la NetApp Console .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Répliquer les données"]



== 10 novembre 2025



=== Licenses and subscriptions



==== Gérer les préférences de facturation

Vous pouvez désormais configurer et gérer les *préférences de facturation* directement dans la NetApp Console. Cette amélioration permet aux administrateurs de définir et de visualiser la facturation de l'utilisation des capacités, des renouvellements et des coûts pour les licences NetApp directes, les abonnements à la place de marché cloud et l'accord Keystone .

Pour plus d'informations, consultez lelink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentation relative aux préférences de facturation"^] .



=== Configuration et administration de la console



==== Agent de console 4.1.0

Cette version de l'agent Console inclut des améliorations de sécurité, des corrections de bugs et les fonctionnalités suivantes :

La version 4.1.0 est disponible pour le mode standard et le mode restreint.

.Indicateurs d'état d'agent renommés
Les indicateurs d'état de l'agent de la console ont été renommés de *Actif* et *Inactif* à *Connecté* et *Déconnecté* afin de rendre leur fonction plus claire.

.Prise en charge de Red Hat Enterprise Linux (RHEL) 9.6 et de Podman 5.4.0
Lors de l'installation manuelle d'un agent Console, celui-ci prend désormais en charge RHEL 9.6 avec Podman 5.4.0. De plus, lors de l'utilisation de RHEL 9 et versions supérieures, NetApp prend en charge podman-compose 1.5.0. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html["Consultez les exigences du système d'exploitation"].



==== Administration de la NetApp Console

Cette version comprend les éléments suivants :

.Nouvelle adresse e-mail pour les notifications de la NetApp Console
L'adresse e-mail qui envoie les notifications de NetApp Console a changé et est désormais *service@console.netapp.com* au lieu de *service@console.bluexp.netapp.com*. NetApp recommande de mettre à jour vos règles de messagerie pour autoriser *service@console.netapp.com* afin de continuer à recevoir les notifications par e-mail de NetApp Console .



=== Classification des données



==== Version 1.48

Cette version de la Classification des données inclut des correctifs de bogues, des améliorations de sécurité et des optimisations de performances.

.Clarté améliorée du suivi de la progression de l'analyse
Les configurations d'analyse incluent désormais des informations améliorées sur l'avancement de l'analyse. Auparavant, une barre de progression ne s'affichait que pendant le déroulement de l'analyse. Désormais, la barre de progression reste visible après la fin de l'analyse pour confirmer que les scans ont été effectués avec succès. Vous pouvez également consulter le nombre de fichiers cartographiés et analysés.

Pour plus d'informations sur les paramètres de numérisation, consultez link:task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["Modifier les paramètres d'analyse de NetApp Data Classification pour vos référentiels"^].



=== Reprise après sinistre



==== Prise en charge du basculement en cascade

Vous pouvez désormais configurer une relation en cascade dans ONTAP et utiliser n'importe quel segment de cette relation de réplication pour la reprise après sinistre.



==== Rétrograder la prise en charge matérielle VMware lors de l'enregistrement

La solution de reprise après sinistre prend désormais en charge la rétrogradation du matériel VMware vers une version antérieure de vSphere lors de l'enregistrement. Cela s'avère utile lorsque l'hôte ESX source exécute une version plus récente que le site de reprise après sinistre.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Créer un plan de réplication dans NetApp Disaster Recovery"].



==== Arrêt en douceur

La reprise après sinistre arrête désormais les machines virtuelles en douceur au lieu de les éteindre brutalement. Si une machine virtuelle donnée met plus de dix minutes à s'éteindre, la procédure de reprise après sinistre l'éteint.



==== Assistance à la création de scripts avant sauvegarde

Vous pouvez désormais injecter des scripts personnalisés dans le flux de travail de basculement pour qu'ils s'exécutent avant la création d'une sauvegarde. Les scripts de pré-sauvegarde vous permettent de contrôler l'état de la machine virtuelle avant la réplication d'un instantané et de préparer une machine virtuelle à une transition. Par exemple, vous pouvez injecter un script qui démonte un montage NFS qui sera remonté à l'aide d'un script différent après le basculement.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Créer un plan de réplication dans NetApp Disaster Recovery"].



=== Résilience aux ransomwares

Cette version comprend des améliorations générales.



=== Cloud Volumes ONTAP



==== Prise en charge NVMe-TCP améliorée

Auparavant, lors du déploiement d'instances Cloud Volumes ONTAP sur NVMe-TCP, il était nécessaire d'obtenir et d'appliquer manuellement les licences NVMe avant le déploiement. Grâce à cette mise à jour, Cloud Volumes ONTAP installe désormais automatiquement les licences NVMe requises lors du déploiement, simplifiant ainsi le processus d'installation.

Pour les déploiements NVMe-TCP existants dépourvus de licences, Cloud Volumes ONTAP applique automatiquement les licences. Vous devez redémarrer le système pour que les licences soient prises en compte.

Pour plus d'informations, consultez https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-client-protocols.html#nvme-tcp["Protocoles clients pris en charge pour Cloud Volumes ONTAP: NVMe-TCP"^] .



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Remplissez votre case de notification de couverture

L'onglet *Surveillance des alertes* de la page *Surveillance* comprend une boîte de notification *Complétez votre couverture* qui apparaît en cas de lacunes de couverture. Cette section répertorie les abonnements dont la capacité ou la date d'expiration est insuffisante, ainsi que les moniteurs sans abonnement. Vous pouvez combler les lacunes en ajoutant des abonnements aux moniteurs existants, en créant de nouveaux moniteurs ou en supprimant les moniteurs inutilisés. Pour en savoir plus, consultez link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Gérer les lacunes de couverture pour les moniteurs d'alerte"].



== 17 octobre 2025



=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP dans Azure est désormais limité aux dernières versions prises en charge

Les déploiements et mises à niveau de Cloud Volumes ONTAP dans Azure via la NetApp Console sont désormais limités aux dernières versions prises en charge. Cela garantit la compatibilité avec le matériel de dernière génération pris en charge par Microsoft et fournit les fonctionnalités et améliorations de sécurité les plus récentes. La console vous invitera à effectuer une mise à niveau vers les versions prises en charge.

Pour plus de détails, reportez-vous à :

* Déploiement: https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-versions.html#azure["Versions ONTAP prises en charge pour les déploiements Cloud Volumes ONTAP"^]
* Mise à niveau: https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html#supported-upgrade-paths["Chemins de mise à niveau pris en charge pour Azure"^]




== 13 octobre 2025



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Colonne de remplacement de la politique QoS dans l'onglet Ressources

L'onglet *Volumes dans les clusters* dans l'onglet *Actifs* inclut désormais une colonne *Remplacement de la politique QoS* qui indique si les règles QoS sont contournées pour les volumes de sauvegarde et de miroir, affichant *vrai* (règles ignorées), *faux* (règles appliquées) ou *N/A* (pour les volumes miroir).


NOTE: Pour les abonnements Keystone v3, cette colonne affiche *N/A* car les politiques QoS ne sont pas applicables dans l'offre v3.



==== Visibilité améliorée des alertes dans la page Aperçu

La page *Aperçu* inclut désormais deux nouvelles sections d'alerte nommées *Alertes non résolues par gravité* et *Alertes Keystone non résolues les plus anciennes*. Pour en savoir plus, consultez link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["Tableau de bord Keystone dans la NetApp Console"].
