---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.



== Services obsolètes



=== Mise en cache de périphérie

Le service de mise en cache de périphérie a été supprimé le 7 août 2024.



=== Kubernetes

La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



=== Rapports de migration

Le service de rapports de migration a été supprimé le 7 août 2024.



=== Résilience opérationnelle

Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.



=== Assainissement

Le service de remédiation a été supprimé le 22 avril 2024.
