---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.

[NOTE]
====
Les services suivants ont été abandonnés :

Mise en cache de périphérie:: Le service de mise en cache de périphérie a été supprimé le 7 août 2024.
Kubernetes:: La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.
Rapports de migration:: Le service de rapports de migration a été supprimé le 7 août 2024.
Résilience opérationnelle:: Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.
Assainissement:: Le service de remédiation a été supprimé le 22 avril 2024.


====


== 08 juin 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent l'amélioration suivante :

*Prise en charge du stockage cloud compatible S3* : NetApp Backup and Recovery pour les charges de travail Volumes prend désormais en charge la sauvegarde vers un stockage cloud compatible S3.

Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Améliorations concernant la restauration de fichiers et de dossiers sur une machine virtuelle invitée* : Vous pouvez désormais restaurer des fichiers et des dossiers à partir d’un instantané sur un stockage principal ou secondaire vers une machine virtuelle Windows invitée. Cette fonctionnalité est désormais prise en charge pour les VM CIFS et SAN.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Vue d'ensemble de la protection des charges de travail Hyper-V"].



=== Classification des données



==== Améliorations générales

Cette version de Data Classification inclut des améliorations de sécurité et de performances.



=== Résilience aux ransomwares



==== Flexibilité accrue pour les stratégies de protection

La solution Ransomware Resilience offre désormais une plus grande flexibilité dans le choix des stratégies de détection des ransomwares. Auparavant, toutes les stratégies de protection contre les ransomwares devaient inclure la détection du chiffrement. Désormais, vous pouvez activer une stratégie de protection contre les ransomwares basée uniquement sur la détection du comportement de l'utilisateur.

Les stratégies de protection peuvent toujours inclure la détection du chiffrement  la détection des comportements suspects des utilisateurs. Le blocage des extensions de fichiers peut également être ajouté à toute stratégie de protection.

Si vous désactivez une partie de la stratégie de protection d'une politique existante, les alertes créées dans le cadre de la version précédente de cette politique ne peuvent être marquées que comme « Résolues » et non comme « Ignorées ». Par exemple, si vous aviez une stratégie de protection qui incluait la détection du chiffrement et le comportement utilisateur suspect, mais que vous avez désactivé la détection du chiffrement, vous ne pouvez résoudre qu'une alerte de chiffrement existante pour cette charge de travail.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Protégez les charges de travail avec les stratégies de protection NetApp Ransomware Resilience"^].



==== Améliorations apportées au playbook SOAR

Les playbooks SOAR de Ransomware Resilience proposent désormais des étapes de remédiation après que vous avez bloqué un utilisateur ou mis un volume hors ligne. Vous pouvez désormais remettre un volume en ligne et débloquer un utilisateur si l'action a été jugée non constitutive d'une menace de type ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer un playbook SOAR"^].



== 03 juin 2026



=== Planification du cycle de vie



==== Mises à jour du nom de la fonctionnalité de planification du cycle de vie

Les fonctionnalités de planification du cycle de vie suivantes ont vu leur nom modifié :

* La fonction de mise à jour technique s'appelle désormais *Actualisation du système*. Découvrez comment link:../use/tech-refresh.html["évaluer une mise à jour du système"].
* La fonctionnalité d'ajout de capacité s'appelle désormais *Extension de stockage*. Découvrez comment link:../use/capacity-add.html["étendre le stockage"].
* La fonctionnalité Renouvellements s'appelle désormais *Renouvellements d'assistance*. Découvrez comment link:../support/task-support-registration.html["s'inscrire pour obtenir de l'aide"].




=== Conseiller numérique



==== Mises à jour du nom du widget Digital Advisor

Les fonctionnalités suivantes de Digital Advisor ont changé de nom :

* La fonction « Actualisation technique » s’appelle désormais « Actualisation du système ». Découvrez comment link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["évaluer une mise à jour du système"].
* La fonctionnalité « Ajout de capacité » s’appelle désormais « Extension de stockage ». En savoir plus link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets Digital Advisor"].
* La fonctionnalité Renouvellements s'appelle désormais Renouvellements d'assistance. En savoir plus link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets Digital Advisor"].




== 26 mai 2026



=== Résilience aux ransomwares



==== Prise en charge de Google Cloud NetApp Volumes (aperçu)

Ransomware Resilience prend désormais en charge la création de groupes de protection pour les charges de travail dans les systèmes Google Cloud NetApp Volumes, ce qui vous permet d’organiser plusieurs charges de travail sous une seule stratégie afin de simplifier la gestion.

Pour plus d’informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Créer un groupe de protection dans Ransomware Resilience"^].



== 25 mai 2026



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Affichage amélioré des mises à jour multiples effectuées le même jour dans la chronologie de l'abonnement

Le graphique de l'historique des abonnements affiche désormais un chiffre lorsque plusieurs mises à jour d'abonnements de types différents ont lieu le même jour, au lieu d'icônes distinctes. Survolez le chiffre pour afficher tous les types de mises à jour de ce jour-là. Le rapport téléchargé comprend une ligne distincte pour chaque mise à jour, vous offrant ainsi un historique complet de toutes les modifications. Pour en savoir plus, consultez link:./integrations/subscription-timeline.html["Consultez la chronologie de vos abonnements Keystone"].



== 18 mai 2026



=== Résilience aux ransomwares



==== Prise en charge de Google Cloud NetApp Volumes (aperçu)

Ransomware Resilience prend désormais en charge les systèmes Google Cloud NetApp Volumes, vous permettant de détecter et de contrer efficacement les menaces de ransomware dans Google Cloud NetApp Volumes. Lorsque vous effectuez une découverte, Ransomware Resilience affiche automatiquement les charges de travail provenant des systèmes Google Cloud NetApp Volumes. Lorsque vous découvrez les systèmes, ils apparaissent dans le tableau de bord de Ransomware Resilience. La prise en charge de Google Cloud NetApp Volumes dans Ransomware Resilience est actuellement en préversion.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Découvrez la résilience face aux ransomwares"^]. Pour des informations sur l'étendue de la prise en charge de Google Cloud NetApp Volumes, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Limites de la résilience face aux ransomwares"^].



==== Améliorations de la restauration propre

La restauration complète prend désormais en charge les rapports. Grâce aux rapports, vous pouvez consulter et évaluer les restaurations complètes, en enregistrant ces informations hors ligne au format CSV.

La restauration propre permet désormais d'interrompre l'analyse. Si vous interrompez l'analyse, vous devez recommencer la restauration propre.

Pour en savoir plus sur les rapports, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Télécharger les rapports dans Ransomware Resilience"^]. Pour en savoir plus sur la récupération, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].



=== Cloud Volumes ONTAP



==== Déploiement simplifié de Cloud Volumes ONTAP dans Azure

Vous pouvez désormais utiliser la création rapide pour déployer Cloud Volumes ONTAP dans Azure, aussi bien pour les configurations à nœud unique que pour les configurations à haute disponibilité (HA). Ce processus simplifié réduit le nombre d'étapes par rapport à la méthode avancée, définit automatiquement les valeurs par défaut sur une seule page et minimise la navigation, rendant le déploiement plus rapide et plus facile.

.Liens associés
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Déployez Cloud Volumes ONTAP dans Azure avec Quick create"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Déployez Cloud Volumes ONTAP à l'aide des options avancées dans Azure"^]




=== Conseiller numérique



==== Revue de bien-être

À compter de juillet 2026, la fonctionnalité « Bilan bien-être » ne sera plus disponible dans Digital Advisor. Pour toute question, veuillez envoyer un courriel à mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].



== 12 mai 2026



=== Cloud Volumes ONTAP



==== Facturation flexible pour Cloud Volumes ONTAP et les services de données dans AWS

NetApp propose des options de facturation améliorées pour vos abonnements Cloud Volumes ONTAP dans AWS, vous offrant un meilleur contrôle sur la façon dont vous payez la capacité Cloud Volumes ONTAP et les services de données NetApp, tels que NetApp Backup and Recovery. Auparavant, toute l’utilisation de Cloud Volumes ONTAP et des services de données était facturée ensemble via l’offre NetApp Intelligent Services (NIS) sur la place de marché AWS.

Suite aux modifications apportées au programme de remises pour entreprises AWS (EDP), NetApp a introduit un abonnement Cloud Volumes ONTAP autonome sur la place de marché AWS qui vous permet de dissocier la facturation de la capacité Cloud Volumes ONTAP de celle des services de données. Cette dissociation vous offre une plus grande flexibilité dans la gestion de vos crédits et coûts EDP. NetApp recommande d'utiliser l'abonnement autonome pour une meilleure gestion des coûts liés à votre utilisation de Cloud Volumes ONTAP, tout en continuant d'utiliser l'abonnement NIS pour la facturation des services de données après le 31 juillet 2026, lorsque les exigences EDP entreront en vigueur.

L'abonnement Cloud Volumes ONTAP autonome sur AWS prend uniquement en charge les packages de licence Essentials ou Freemium valides, basés sur la capacité. Le package Professional n'est pas pris en charge. Vous pouvez choisir le mode de facturation qui correspond le mieux à vos besoins :

* *Abonnement Cloud Volumes ONTAP autonome (recommandé)* : payez votre utilisation de Cloud Volumes ONTAP via l’abonnement autonome sur la place de marché AWS, tout en continuant à facturer les services de données via l’abonnement NIS. C’est l’option recommandée pour la plupart des clients qui disposent à la fois d’un abonnement autonome et d’un abonnement NIS associés à leur compte AWS dans la NetApp Console.
* *Abonnement NIS combiné* : payez à la fois Cloud Volumes ONTAP et les services de données ensemble via l'inscription NIS existante. La formule combinée sera valable pour les clients existants qui ont uniquement des abonnements NIS associés à leur compte AWS dans la NetApp Console. Cependant, NetApp recommande de définir vos préférences de facturation pour votre utilisation de Cloud Volumes ONTAP et de passer à l'abonnement autonome pour une meilleure gestion des coûts.


Selon votre type d'abonnement, vous bénéficiez des scénarios suivants :

.Abonnement autonome uniquement (nouveaux clients)
Si vous ne disposez que d'un abonnement AWS autonome associé à votre compte AWS dans la NetApp Console et d'aucun abonnement NIS, vous ne pouvez sélectionner que le pack de licences Essentials lors du déploiement. L'option de service de données *Backup and Recovery* ne vous est pas disponible.

.Abonnements autonomes et NIS (clients existants)
Si votre compte AWS comprend à la fois un abonnement NIS et un abonnement autonome, et que vous n'avez pas défini de préférence de facturation dans l'onglet *Préférences de facturation* de la NetApp Console, l'utilisation de Cloud Volumes ONTAP continue d'être facturée par défaut via NIS. Ceci est également le comportement par défaut pour toute instance Cloud Volumes ONTAP exécutant le package Professional, car l'offre autonome ne prend pas en charge Professional. Vous pouvez définir une préférence de facturation et choisir le mode de facturation de chaque service :

* Configurez l'abonnement autonome comme compte de facturation préféré pour Cloud Volumes ONTAP (avec le package Essentials). Si vous ne possédez que le package Professional, vous pouvez le convertir en package Essentials et facturer votre utilisation de Cloud Volumes ONTAP en définissant la préférence de facturation. Nous recommandons cette méthode car elle vous permet de gérer vos crédits EDP Cloud Volumes ONTAP plus efficacement.
* Utilisez l'abonnement NIS pour la facturation des services de données ou l'utilisation de Cloud Volumes ONTAP via le pack Professionnel. Lors du déploiement, activez le service de données *Backup and Recovery* et sélectionnez le pack de licences Professionnel pour facturer les services de données via l'abonnement NIS.


.Abonnement NIS uniquement (clients existants)
Ceci s'applique si vous êtes déjà client et disposez d'abonnements NIS associés à votre compte AWS. Vous pouvez continuer à facturer Cloud Volumes ONTAP et les services de données ensemble comme actuellement. Cependant, NetApp recommande de passer à l'approche d'abonnement autonome pour une meilleure gestion des coûts de votre utilisation de Cloud Volumes ONTAP :

* Abonnez-vous à une nouvelle fiche produit autonome sur le portail AWS.
* Associez l'abonnement autonome à votre compte AWS.
* Définissez votre préférence de facturation sur l’abonnement autonome pour l’utilisation de Cloud Volumes ONTAP avec le forfait Essentials.
* (Le cas échéant) Convertissez votre forfait Professional en forfait Essentials et définissez votre préférence de facturation.
* Continuez à facturer les services de données via votre abonnement NIS.



NOTE: Aucun comptage en double ne se produit lorsque vous utilisez plusieurs types d'abonnement ou que vous migrez entre des annonces.

.Lien associé
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["Configurer les licences pour Cloud Volumes ONTAP dans AWS"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["Modifier les méthodes de facturation des licences de capacité"^]




== 11 mai 2026



=== Configuration et administration de la console



==== Agent Console 4.7.0

La version 4.7.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité et des corrections de bugs.



==== Administration de la NetApp Console

Cette version inclut la fonctionnalité suivante.

.Vérifiez l'organisation de votre Console
Par défaut, Digital Advisor affiche tous les comptes NetApp associés à votre entreprise, plutôt qu'à votre seule organisation Console. Pour limiter l'affichage dans Digital Advisor à un compte spécifique, vérifiez le compte professionnel que vous souhaitez utiliser avec votre organisation Console. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["Découvrez comment vérifier votre organisation Console"^]



=== Sauvegarde et récupération



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Protection des machines virtuelles sur stockage SAN* : Vous pouvez désormais protéger les machines virtuelles sur le stockage objet SAN.
* *Améliorations de la restauration vers un emplacement alternatif* : Vous pouvez désormais restaurer vers un emplacement alternatif à partir des emplacements principal et secondaire pour les machines virtuelles sur un stockage SAN.
* *Restaurez des fichiers et des dossiers sur une machine virtuelle invitée* : Vous pouvez désormais restaurer des fichiers et des dossiers à partir d’un instantané du stockage principal vers une machine virtuelle Windows invitée. Cette fonctionnalité est prise en charge uniquement pour les machines virtuelles CIFS.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Vue d'ensemble de la protection des charges de travail Hyper-V"].



==== Améliorations des charges de travail KVM

Cette version introduit l'amélioration suivante pour les charges de travail KVM :

*Restauration vers un autre emplacement* : Vous pouvez désormais restaurer les machines virtuelles KVM vers un autre emplacement (cette fonctionnalité est désormais disponible en disponibilité générale).

Pour plus de détails sur la protection des charges de travail KVM, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Présentation de la protection des charges de travail KVM"] .



==== Améliorations des charges de travail Oracle Database

Cette version introduit les améliorations suivantes pour les charges de travail de la base de données Oracle :

* *Prise en charge d'Oracle AI Database 26ai* : NetApp Backup and Recovery prend désormais en charge Oracle AI Database 26ai.
* *Prise en charge de la vérification des sauvegardes* : Vous pouvez désormais configurer des stratégies de sauvegarde pour vérifier automatiquement l’intégrité de vos sauvegardes de base de données Oracle.


Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Vue d'ensemble de la protection des workloads Oracle Database"].



==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

* *Prise en charge des datastores répartis pour les groupes de protection* : Vous pouvez désormais choisir le comportement des groupes de protection lors de la protection de machines virtuelles dont les disques virtuels s’étendent sur plusieurs datastores.
* *Prise en charge du clonage* : Vous pouvez désormais créer des clones d’instantanés de machines virtuelles à partir du stockage principal et secondaire.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.05.1*: Cette version inclut Trident Protect 26.05.1.
* *Restauration sur place pour les applications basées sur des machines virtuelles* : Vous pouvez désormais restaurer les applications basées sur des machines virtuelles dans l’espace de noms et le cluster d’origine.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



=== Classification des données



==== Page de configuration améliorée

La page de configuration de Data Classification a été mise à jour et améliorée, offrant ainsi une expérience utilisateur optimisée pour la gestion des paramètres, des systèmes, l'activation des analyses et la surveillance de l'état du système. La nouvelle page de configuration propose la fonctionnalité existante dans un format plus intuitif, avec en plus la possibilité de filtrer les systèmes par type, état d'erreur et état d'analyse. La nouvelle page fournit également un récapitulatif des systèmes connectés et un aperçu des analyses actives et configurées.

Examinez un link:https://youtu.be/_8YJ3KyZ7nI["visite vidéo"^]. Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Analyser les sources de données avec la classification des données"^].



==== Rôle d'administrateur de conformité IAM

La classification des données prend désormais en charge un rôle d'administrateur de conformité permettant de gérer les autorisations dans Data Classification. Le rôle d'administrateur de conformité n'a pas accès aux ressources, y compris les agents Console et les espaces de travail. Les utilisateurs disposant du rôle d'administrateur de conformité doivent être associés à au moins un autre rôle.

Lors de l'installation de Data Classification, vous devez disposer d'un rôle d'administrateur de la plateforme Console ou du rôle d'administrateur de conformité.

Si vous êtes déjà utilisateur, votre accès devrait continuer normalement. Par exemple, un rôle de plateforme qui possède un rôle d'administrateur de dossier ou de projet dispose d'un accès existant.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Rôles de la classification des données"^].



==== Déployez la classification des données avec OVA

NetApp Data Classification prend désormais en charge le déploiement avec VMware Open Virtual Appliance (OVA), offrant une stratégie de déploiement simplifiée pour les environnements VMware vSphere sur site.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Déployez la classification des données avec OVA"^].



=== Reprise après sinistre



==== Prise en charge des charges de travail basées sur Kubernetes (aperçu)

NetApp Disaster Recovery inclut désormais la prise en charge des charges de travail basées sur Kubernetes. Avec la prise en charge de Kubernetes, vous pouvez protéger les applications exécutées sur des clusters Kubernetes, y compris les environnements de virtualisation OpenShift. Disaster Recovery prend en charge link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["toute version de Kubernetes actuellement prise en charge par Trident Protect"^], assurant une intégration transparente et des capacités de reprise après sinistre robustes pour les applications conteneurisées.

Principales caractéristiques de la prise en charge des charges de travail basées sur Kubernetes :

* **Large compatibilité** : La reprise après sinistre prend en charge toutes les versions de Kubernetes compatibles avec Trident Protect, y compris Red Hat OpenShift Virtualization.
* **Protection centrée sur l'application** : Vous pouvez désormais protéger les charges de travail Kubernetes au niveau de l'application, garantissant ainsi la reprise des services critiques lors des basculements.
* **Orchestration simplifiée** : La reprise après sinistre offre des flux de travail intuitifs pour automatiser la sauvegarde et la réplication des charges de travail Kubernetes, en tirant parti de la même technologie efficace SnapMirror utilisée pour les environnements VMware.


La prise en charge des charges de travail basées sur Kubernetes est actuellement en préversion. Pour commencer à protéger les charges de travail basées sur Kubernetes, consultez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Exigences de Kubernetes pour NetApp Disaster Recovery"^].



=== Résilience aux ransomwares



==== Améliorations de la restauration propre

La restauration propre prend désormais en charge la récupération vers un emplacement alternatif, ce qui vous permet de restaurer des volumes sur différents systèmes, machines virtuelles de stockage et agrégats gérés par le même agent Console. De plus, la restauration propre a supprimé la limitation de sept jours dans la recherche de snapshots exploitables pour la récupération. La restauration propre continue désormais de rechercher un point de récupération viable parmi les snapshots disponibles, quelle que soit la distance par rapport à l'événement de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].



==== Assistance Google SecOps SIEM

Ransomware Resilience prend désormais en charge la gestion des informations et des événements de sécurité (SIEM) avec Google SecOps, vous permettant d'envoyer automatiquement des données à Google SecOps pour une analyse et une détection des menaces simplifiées.

Pour plus d'informations sur la configuration, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Connectez NetApp Ransomware Resilience à un SIEM"^].



==== La prise en charge d'Azure NetApp Files est désormais disponible pour tous

Ransomware Resilience prend désormais en charge les systèmes Azure NetApp Files, vous permettant de détecter et de contrer efficacement les menaces de ransomware dans Azure NetApp Files. Lors de la découverte des charges de travail, Ransomware Resilience présente désormais Azure NetApp Files et les affiche dans le tableau de bord de protection. La prise en charge d’Azure NetApp Files par Ransomware Resilience inclut des stratégies de détection et de protection uniquement avec des instantanés. La prise en charge d’Azure NetApp Files est désormais généralement disponible (GA).

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Découvrez la résilience face aux ransomwares"^].



==== Prise en charge SOAR pour le blocage des utilisateurs

Ransomware Resilience prend désormais en charge le blocage individuel des utilisateurs avec Google SecOps et les playbooks SOAR de Splunk. Avec cette addition, vous pouvez automatiser le blocage des utilisateurs lorsque Ransomware Resilience détecte une activité utilisateur suspecte, telle qu'une violation de données ou une suppression massive de données.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer un playbook SOAR"^].



== 5 mai 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.05* : Cette version inclut Trident Protect 26.05.
* *Mise à niveau de Trident Protect depuis Backup and Recovery* : Si votre cluster Kubernetes exécute Trident Protect 26.05 ou une version plus récente, vous pouvez désormais mettre à niveau Trident Protect directement depuis Backup and Recovery.
* *Prise en charge native de la protection des machines virtuelles* : Vous pouvez désormais créer des applications basées sur des machines virtuelles, ce qui vous permet de protéger ces dernières de la même manière que n’importe quelle autre application.
* *Transformations des ressources* : Vous pouvez désormais utiliser des transformations de ressources et des modèles de transformation de ressources pour ajouter, supprimer et modifier les attributs des ressources pendant le processus de restauration.
* *Afficher les ressources protégées* : Vous pouvez désormais consulter les ressources incluses dans chaque point de récupération d’une application et télécharger un rapport JSON détaillé. Vous bénéficiez ainsi d’une visibilité complète sur vos points de récupération et simplifiez la conformité aux audits.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



== 27 avril 2026



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Étiquette de capacité provisionnée renommée

L'intitulé *Capacité provisionnée* est renommé *Capacité volumique provisionnée*. Le nouvel intitulé est également reflété dans les rapports CSV et Excel associés.



==== Basculement des prévisions pour la rafale accumulée

Vous pouvez désormais utiliser le bouton *Prévisions* dans la vue *Consommation cumulée des pics* de l’onglet *Tendance de consommation* pour projeter la consommation cumulée des pics pour les 120 prochains jours à compter de la date actuelle. Pour en savoir plus, consultez link:./integrations/consumption-tab.html#view-forecast-data["Consulter les données prévisionnelles"].



== 20 avril 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail VMware

Dans cette version, les charges de travail VMware introduisent l'amélioration suivante :

*ASA r2 prise en charge SAN* : Les charges de travail VMware prennent désormais en charge la protection des machines virtuelles sur des banques de données VMFS hébergées par des environnements NetApp ASA r2 SAN uniquement.

Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



== 13 avril 2026



=== Configuration et administration de la console



==== Agent Console 4.6.0

La version 4.6.0 prend en charge à la fois le mode standard et le mode restreint.

Cette version de l'agent Console inclut des améliorations de sécurité et des corrections de bugs, ainsi que la fonctionnalité nouvelle suivante.

.Prise en charge des vérifications de configuration de l'espace disque
Vous pouvez vérifier que l'espace disque requis pour l'agent Console est disponible à l'aide des contrôles de configuration. Vous pouvez effectuer des contrôles de configuration depuis la Console ou la console de maintenance de l'agent. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["En savoir plus sur l'exécution des vérifications de configuration sur l'agent Console"^]

.Mettre à niveau un agent Console déployé par vCenter à l'aide d'une image ISO
Si vous avez déployé un agent Console dans vCenter à l'aide d'un fichier OVA, vous pouvez désormais le mettre à niveau vers une nouvelle version en montant une image ISO sur la machine virtuelle et en exécutant la mise à niveau depuis la console de maintenance de la machine virtuelle. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Découvrez comment mettre à niveau un agent Console déployé par vCenter"^]



=== Sauvegarde et récupération



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent l'amélioration suivante :

*NetApp MetroCluster configurations actives/actives prises en charge* : NetApp Backup and Recovery for Volumes workloads prend désormais en charge MetroCluster dans la configuration active-active.

Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



==== Améliorations des charges de travail Kubernetes

Dans cette version, les charges de travail Kubernetes introduisent les améliorations suivantes en matière de politique de protection :

* *Modifier les politiques de protection* : Vous pouvez désormais modifier les politiques de protection des charges de travail Kubernetes si vous devez les modifier.
* *Prise en charge des sauvegardes disque à disque* : Vous pouvez désormais configurer les politiques de protection Kubernetes avec une architecture de sauvegarde disque à disque.
* *Prise en charge des buckets de stockage Google Cloud Platform* : Vous pouvez désormais configurer les politiques de protection Kubernetes pour effectuer des sauvegardes sur des buckets de stockage Google Cloud Platform.


Pour plus d'informations sur les politiques de protection, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Créez et gérez des politiques de protection dans NetApp Backup and Recovery"].

Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Gestion des tâches améliorée* : NetApp Backup and Recovery gère désormais plusieurs tâches simultanées plus efficacement.
* *Prise en charge SAN (aperçu)* : NetApp Backup and Recovery prend désormais en charge la protection des machines virtuelles Hyper-V stockées sur un stockage SAN.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Vue d'ensemble de la protection des charges de travail Hyper-V"].



==== Améliorations des charges de travail KVM

Dans cette version, les charges de travail KVM introduisent les améliorations suivantes :

* *Gestion des tâches améliorée* : NetApp Backup and Recovery gère désormais plusieurs tâches simultanées plus efficacement.
* *Restauration vers un autre emplacement (aperçu)* : Vous pouvez désormais restaurer les machines virtuelles KVM vers un autre emplacement. Pour plus d'informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-restore.html["Restaurez les machines virtuelles KVM avec NetApp Backup and Recovery"].


Pour plus de détails sur la protection des charges de travail KVM, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Présentation de la protection des charges de travail KVM"] .



==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

* *Protection basée sur les étiquettes* : Backup and Recovery for VMware workloads prend désormais en charge la protection basée sur les étiquettes pour les machines virtuelles stockées sur des volumes NFS et VMFS, ce qui vous permet de créer des groupes de protection à partir des étiquettes vCenter au lieu de machines virtuelles ou de datastores individuels. Lorsque vous étiquetez des machines virtuelles et des datastores dans vCenter, Backup and Recovery les découvre et les inclut automatiquement dans les sauvegardes futures sans aucune maintenance manuelle des groupes. Pour plus d'informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Créer et gérer des groupes de protection"].
* *Restauration sur un système de stockage alternatif* : Vous pouvez désormais restaurer des machines virtuelles sur un système de stockage alternatif même si le système de stockage principal est totalement indisponible. Pour plus d'informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore.html["Restaurer les charges de travail VMware"].
* *Restauration de fichiers sur des machines virtuelles Linux* : Vous pouvez désormais restaurer des fichiers et des dossiers de machines virtuelles sur des machines virtuelles Linux. Pour plus d'informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurer les fichiers et les dossiers"].
* *Prise en charge des machines virtuelles proxy lors de la restauration de fichiers et de dossiers* - Vous pouvez désormais restaurer des fichiers et des dossiers à partir de disques virtuels à l'aide d'une machine virtuelle proxy lorsque vous préférez ne pas attacher le disque virtuel à la machine virtuelle d'origine. Pour plus d'informations, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurer les fichiers et les dossiers"].
* *Recherche récursive de fichiers et de dossiers* - Vous pouvez désormais rechercher un fichier ou un dossier spécifique sur l'ensemble d'un disque virtuel. Pour plus d'informations, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurer les fichiers et les dossiers"].
* *Gestion des tâches améliorée* : NetApp Backup and Recovery gère désormais plusieurs tâches simultanées plus efficacement.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



=== Classification des données



==== Améliorations générales

Cette version de Data Classification inclut des correctifs de bogues, des améliorations de sécurité et des optimisations de performances.



=== Hiérarchisation du cloud



==== NetApp Cloud Tiering n'est plus proposé

NetApp Cloud Tiering n'est plus disponible à l'achat ni au renouvellement de licence depuis le 26 avril 2026.

Les clients existants peuvent continuer à utiliser et à bénéficier du support pour NetApp Cloud Tiering jusqu'à l'expiration de leur abonnement ou de leur contrat de licence. Après l'expiration de l'abonnement, les clients n'auront plus accès aux fonctionnalités ou au support de NetApp Cloud Tiering.

NetApp recommande aux clients de travailler avec leur représentant NetApp pour migrer leurs licences de hiérarchisation existantes vers des licences ONTAP FabricPool, qui offrent la fonctionnalité de hiérarchisation des données dans ONTAP. Voir link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["Installez une licence FabricPool sur un cluster ONTAP"] pour plus d'informations sur la configuration de la hiérarchisation des données dans ONTAP à l'aide de FabricPool.

* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-Notice2.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_9L2PauNXYE0fOs0RIz8KK2q5Jb6sg8Yv-97NNJ53ceAab9UAqpKOrAvByxsOWqhIQHNCHgFfM0q3TI["NetApp Cloud Tiering Avis de fin de disponibilité"]
* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-FAQ-v3.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_rplJe_ZtlY4PQAQRQlewsDa0W4JR55muT0KCThR46zI7-uOhIYfVsxODDKFrnYYvy5uZzvhEKHOwBI["NetApp Cloud Tiering FAQ sur la fin de disponibilité"]




=== Reprise après sinistre



==== La prise en charge de Google Cloud VMware Engine (GCVE) est désormais généralement disponible (GA)

NetApp Disaster Recovery pour GCVE est désormais disponible en disponibilité générale (GA). Avec la prise en charge GA, Disaster Recovery pour GCVE prend désormais en charge :

* *Instantanés gérés par la plateforme :* Gérez les sauvegardes et les politiques de rétention de manière transparente via ONTAP ou Google Cloud Platform (GCP).
* *Plusieurs banques de données par plan de réplication :* Simplifiez vos plans de reprise après sinistre en consolidant plusieurs banques de données dans une seule stratégie de réplication.
* *Forcer le basculement en cas d'indisponibilité du site source :* Basculer vers un site de reprise après sinistre si la source est indisponible.
* *Différer la resynchronisation SnapMirror et restaurer la réplication à la demande :* Différez les resynchronisations SnapMirror pour éviter tout impact sur les charges de travail de production pendant les périodes de pointe grâce à l’option « skip protect », puis restaurez la réplication à la demande ultérieurement avec l’option « re-protect ».


Pour plus d'informations sur la prise en charge de GCVE, découvrez link:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["Configurations prises en charge pour NetApp Disaster Recovery"^].



=== Résilience aux ransomwares



==== Restauration propre

Ransomware Resilience prend désormais en charge les restaurations propres, une nouvelle option de récupération qui vous aide à vous remettre rapidement et facilement des attaques de ransomware. Les restaurations propres offrent des flux de travail guidés qui identifient les points de restauration optimaux pour remettre vos charges de travail en service tout en minimisant l'interruption. Les flux de travail dans la restauration propre fournissent également des informations au niveau fichier sur vos données, garantissant que vous pouvez restaurer des charges de travail exemptes de logiciels malveillants, ce qui empêche toute réinfection et minimise la perte de données.

Pour en savoir plus sur les configurations prises en charge et sur la manière de configurer votre système pour une restauration complète, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore.html["Créer un environnement de récupération isolé"^]. Pour en savoir plus sur la procédure de restauration complète, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].



==== Prise en charge SIEM pour Splunk Enterprise

Ransomware Resilience offre désormais une prise en charge de la gestion des informations et des événements de sécurité (SIEM) pour Splunk Enterprise, vous permettant de centraliser les données de journalisation et d'événements et de rationaliser l'analyse et la détection des menaces.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Connectez NetApp Ransomware Resilience à un SIEM"^].



==== Amélioration de la détection du comportement des utilisateurs

Les informations relatives aux incidents de violation de données sont désormais conservées pendant 13 mois après un incident, ce qui permet une conservation des données plus longue pour vos besoins de reporting.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-user-behavior.html["Découvrez la détection du comportement des utilisateurs"^].

Réplication :leveloffset: +1



=== Gestion de la réplication pour les relations existantes avec FSx pour ONTAP

La gestion des relations de réplication pour les systèmes de fichiers FSx for ONTAP, en tant que source ou cible, est désormais disponible dans NetApp Workload Factory.

link:https://docs.netapp.com/us-en/data-services-replication/task-managing-replication.html["Gérer la réplication des données"]



=== Cloud Volumes ONTAP



==== Prise en charge améliorée de Cloud Volumes ONTAP avec les machines virtuelles Google Cloud C3

Cloud Volumes ONTAP prend désormais en charge de manière améliorée les machines virtuelles de la série Google Cloud C3, ce qui permet d'activer les fonctionnalités supplémentaires suivantes :

* Dans vos déploiements Cloud Volumes ONTAP, vous pouvez basculer entre différents types d'instances au sein de la famille C3.
* Lors du changement de type d'instance, si vous sélectionnez c3-standard-44 ou c3-standard-88 et leurs variantes LSSD comme machine virtuelle cible, le service réseau Google applique automatiquement le niveau de réseau de sortie Tier-1. Si vous choisissez une autre variante C3, le niveau de réseau de sortie est défini sur Standard.
+

NOTE: Le passage au niveau 1 du réseau de sortie engendre des coûts supplémentaires. Prévoyez le déploiement et la mise à niveau en conséquence.

* Si vous sélectionnez les variantes SSD locales (LSSD) de C3, le cache Flash est activé par défaut. Vous ne pouvez pas changer de variante LSSD de C3 dans votre déploiement Cloud Volumes ONTAP, même si la variante cible prend en charge le cache Flash.
* Sur vos machines virtuelles C3, vous pouvez désormais ajouter des volumes aux agrégats nouveaux et existants.
* Vous pouvez modifier les paramètres IOPS et de débit lors de l’ajout de volumes via la NetApp Console ou en utilisant l’ `PUT /gcp/vsa/aggregates/{workingEnvironmentId}/{aggregateName}` API.


.Liens associés
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurations prises en charge pour Cloud Volumes ONTAP dans Google Cloud"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#cloud-volumes-ontap-support-for-next-generation-google-cloud-vms["Prise en charge de Cloud Volumes ONTAP pour les machines virtuelles Google Cloud de nouvelle génération"^]




== 31 mars 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail Oracle Database

Cette version introduit l'amélioration suivante pour les charges de travail Oracle Database :

* *Prise en charge des hôtes en cluster* : Vous pouvez désormais détecter et protéger les bases de données Oracle Real Application Clusters (RAC) utilisant Oracle Automatic Storage Management (ASM) et déployées à l’aide de VMDK sur des systèmes de fichiers VMFS. Pour plus d’informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-discover-oracle.html["Découvrez les charges de travail Oracle Database"].
* *Prise en charge du catalogue RMAN* : Vous pouvez désormais configurer Backup and Recovery pour stocker les métadonnées de protection dans le catalogue de récupération RMAN, ce qui assure la redondance et la conservation à long terme en cas de perte du fichier de contrôle cible. Pour plus d’informations, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-configure-oracle-database.html["Configurer une base de données Oracle"].


Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Vue d'ensemble de la protection des workloads Oracle Database"].



=== Résilience aux ransomwares



==== Plan d'action SOAR pour Google SecOps

Ransomware Resilience propose désormais un guide d'orchestration, d'automatisation et de réponse en matière de sécurité (SOAR) pour link:https://github.com/chronicle/content-hub/tree/main/content/response_integrations/third_party/partner/netappransomwareresilience["Google SecOps"^]. Ce guide facilite la gestion des réponses aux menaces, automatise les tâches et les tests, et prend en charge les actions essentielles de réponse aux ransomwares, notamment la création de snapshots et la mise hors ligne d'un volume.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer les playbooks SOAR"^].



== 30 mars 2026



=== Keystone

Nouvelles améliorations dans le tableau de bord Keystone dans la NetApp Console:



==== Au-dessus de la capacité de pointe sur le graphique de consommation historique

Le graphique de consommation historique de l'onglet *Tendance de consommation* met désormais en évidence les utilisations dépassant la limite de pointe. Pour en savoir plus, consultez link:./integrations/consumption-tab.html["Consultez les tendances de consommation de vos abonnements Keystone"].



==== Prévisions d'utilisation des capacités

Vous pouvez utiliser le bouton *Prévisions* dans la vue *Historique de consommation* de l'onglet *Tendance de consommation* pour projeter l'utilisation des capacités pour les 120 prochains jours à compter de la date actuelle. Pour en savoir plus, consultez link:./integrations/consumption-tab.html#view-forecast-data["Consulter les données prévisionnelles"].



==== ID de suivi dans l'exportation d'abonnement

Le rapport d'abonnements téléchargé depuis la page *Abonnements* inclut désormais l'*Tracking ID* dans les données de niveau de service de performance, aussi bien aux formats Excel que CSV.



==== Mises à jour de la visibilité des colonnes de la page Subscriptions

Sur la page *Abonnements*, la colonne *Version Keystone* est désormais masquée par défaut, et la colonne *Abonnements liés* n'apparaît que lorsque des abonnements liés sont disponibles.



== 16 mars 2026



=== Sauvegarde et récupération



==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

*Prise en charge de la cohérence des machines virtuelles par niveau de planification* : Vous pouvez désormais activer les sauvegardes cohérentes au niveau des machines virtuelles et des applications pour des niveaux de planification spécifiques lors de la configuration des stratégies de protection pour les charges de travail VMware. Les niveaux annuels, mensuels et hebdomadaires sont pris en charge.

Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



== 12 mars 2026



=== Résilience aux ransomwares



==== Playbooks SOAR pour Microsoft Sentinel et Splunk

Ransomware Resilience propose désormais des playbooks d'orchestration, d'automatisation et de réponse en matière de sécurité (SOAR) pour link:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/NetApp%20Ransomware%20Resilience/Playbooks["Microsoft Sentinel"^] et link:https://github.com/splunk-soar-connectors/netappransomwareresilience["Splunk"^]. Les playbooks permettent une gestion plus facile des réponses aux menaces, automatisant les tests des tâches et les efforts essentiels de réponse aux ransomwares, y compris la création de snapshots et la mise hors ligne d'un volume.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Intégrer les playbooks SOAR"^].
