---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console. 
---
= Modifications récentes dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie de la NetApp Console.  Pour un historique complet des versions, accédez aulink:release-notes-index.html["ensemble complet de notes de version"] pour chaque service individuel.



== Caractéristiques administratives

Cette section décrit les nouvelles fonctionnalités liées aux fonctionnalités d'administration de la NetApp Console : organisations, identification et accès, agents de console, informations d'identification du fournisseur de cloud, etc.



== Alertes



== Amazon FSx pour ONTAP



== Stockage Amazon S3



== Stockage d'objets blob Azure



== Azure NetApp Files



== Sauvegarde et récupération



== Classification des données



== Cloud Volumes ONTAP



== Copier et synchroniser



== Conseiller numérique



== Licenses and subscriptions



=== 06 octobre 2025



==== BlueXP est désormais NetApp Console

La NetApp Console, construite sur la base BlueXP améliorée et restructurée, fournit une gestion centralisée du stockage NetApp et des NetApp Data Services dans les environnements sur site et cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée, hautement sécurisée et conforme.

Pour plus de détails sur ce qui a changé, consultez lelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notes de version de la NetApp Console"] .



=== 10 mars 2025



==== Possibilité de supprimer des abonnements

Vous pouvez désormais supprimer les abonnements du portefeuille numérique si vous vous en êtes désabonné.



==== Afficher la capacité consommée pour les abonnements Marketplace

Lorsque vous consultez les abonnements PAYGO, vous pouvez désormais visualiser la capacité consommée de l'abonnement.



=== 10 février 2025

Le BlueXP digital wallet a été repensé pour une utilisation plus facile et offre désormais une gestion supplémentaire des abonnements et des licences.



==== Nouveau tableau de bord de présentation

La page d'accueil du portefeuille numérique dispose d'un tableau de bord mis à jour de vos licences NetApp et de vos abonnements Marketplace, avec la possibilité d'explorer en détail des services spécifiques, des types de licences et des actions requises.



==== Configuration des abonnements aux informations d'identification

Le BlueXP digital wallet vous permet désormais de configurer vos abonnements aux identifiants des fournisseurs. En règle générale, vous le faites lorsque vous souscrivez pour la première fois à un abonnement Marketplace ou à un contrat annuel. Auparavant, la modification des informations d'identification de l'abonnement ne pouvait être effectuée que sur la page Informations d'identification.



==== Associer des abonnements à des organisations

Vous pouvez désormais mettre à jour l'organisation à laquelle un abonnement est associé directement à partir du portefeuille numérique.



==== Gestion des licences Cloud Volume ONTAP

Vous gérez désormais les licences Cloud Volumes ONTAP via la page d'accueil ou l'onglet *Licences directes*. Utilisez l'onglet *Abonnements Marketplace* pour afficher les informations de votre abonnement.



=== 5 mars 2024



==== BlueXP disaster recovery

Le BlueXP digital wallet vous permet désormais de gérer les licences pour la BlueXP disaster recovery. Vous pouvez ajouter des licences, mettre à jour des licences et afficher les détails sur la capacité sous licence.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Apprenez à gérer les licences pour les services de données BlueXP"]



=== 30 juillet 2023



==== Améliorations des rapports d'utilisation

Plusieurs améliorations des rapports d’utilisation de Cloud Volumes ONTAP sont désormais disponibles :

* L'unité TiB est désormais incluse dans le nom des colonnes.
* Un nouveau champ _node(s)_ pour les numéros de série est désormais inclus.
* Une nouvelle colonne _Type de charge de travail_ est désormais incluse dans le rapport d’utilisation des machines virtuelles de stockage.
* Les noms d’environnement de travail sont désormais inclus dans les rapports d’utilisation des machines virtuelles de stockage et des volumes.
* Le type de volume _fichier_ est désormais étiqueté _Primaire (lecture/écriture)_.
* Le type de volume _secondaire_ est désormais étiqueté _Secondaire (DP)_.


Pour plus d'informations sur les rapports d'utilisation, reportez-vous à https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Télécharger les rapports d'utilisation"] .



== Reprise après sinistre



== Systèmes de la série E



== Planification du cycle de vie



== Mise en cache de périphérie

Le service de mise en cache de périphérie a été supprimé le 7 août 2024.



== Google Cloud NetApp Volumes



== Stockage Google Cloud



== Keystone



== Kubernetes

La prise en charge de la découverte et de la gestion des clusters Kubernetes a été supprimée le 7 août 2024.



== Rapports de migration

Le service de rapports de migration a été supprimé le 7 août 2024.



== Clusters ONTAP sur site



== Résilience opérationnelle

Les fonctionnalités de résilience opérationnelle ont été supprimées le 22 août 2025.



== Résilience aux ransomwares



== Assainissement

Le service de remédiation a été supprimé le 22 avril 2024.



== Réplication



== Mises à jour logicielles



== StorageGRID



== Hiérarchisation du cloud



=== 06 octobre 2025



==== La BlueXP tiering est désormais NetApp Cloud Tiering

La BlueXP tiering a été renommée NetApp Cloud Tiering.



==== BlueXP est désormais NetApp Console

La NetApp Console, construite sur la base BlueXP améliorée et restructurée, fournit une gestion centralisée du stockage NetApp et des NetApp Data Services dans les environnements sur site et cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée, hautement sécurisée et conforme.

Pour plus de détails sur ce qui a changé, consultez lelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notes de version de la NetApp Console"] .



=== 09 août 2023



==== Utiliser un préfixe personnalisé pour le nom du bucket

Auparavant, vous deviez utiliser le préfixe « fabric-pool » par défaut lors de la définition du nom du bucket, par exemple _fabric-pool-bucket1_.  Vous pouvez désormais utiliser un préfixe personnalisé lors de la dénomination de votre bucket.  Cette fonctionnalité est disponible uniquement lors de la hiérarchisation des données vers Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Apprendre encore plus"] .



==== Rechercher un cluster sur tous les connecteurs BlueXP

Si vous utilisez plusieurs connecteurs pour gérer tous les systèmes de stockage de votre environnement, certains clusters sur lesquels vous souhaitez implémenter la hiérarchisation peuvent se trouver dans des connecteurs différents.  Si vous n'êtes pas sûr du connecteur qui gère un certain cluster, vous pouvez effectuer une recherche parmi tous les connecteurs à l'aide de Cloud Tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Apprendre encore plus"] .



=== 4 juillet 2023



==== Ajuster la bande passante pour transférer les données inactives

Lorsque vous activez Cloud Tiering, ONTAP peut utiliser une quantité illimitée de bande passante réseau pour transférer les données inactives des volumes du cluster vers le stockage d'objets.  Si vous remarquez que la hiérarchisation du trafic affecte les charges de travail normales des utilisateurs, vous pouvez limiter la quantité de bande passante pouvant être utilisée pendant le transfert. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Apprendre encore plus"] .



==== Événement de hiérarchisation affiché dans le centre de notifications

L'événement de hiérarchisation « Hiérarchiser les données supplémentaires du cluster <nom> vers le stockage d'objets pour augmenter l'efficacité de votre stockage » apparaît désormais sous la forme d'une notification lorsqu'un cluster hiérarchise moins de 20 % de ses données froides, y compris les clusters qui ne hiérarchisent aucune donnée.

Cette notification est une « recommandation » pour vous aider à rendre vos systèmes plus efficaces et à économiser sur les coûts de stockage. Il fournit un lien vers le https://www.netapp.com/data-services/tiering/tco-calculator/["Calculateur du coût total de possession et des économies de Cloud Tiering"^] pour vous aider à calculer vos économies.



== Mise en cache des volumes



== Usine de charge de travail



=== 06 octobre 2025



==== BlueXP workload factory désormais NetApp Workload Factory

BlueXP a été renommé et repensé pour mieux refléter le rôle qu'il joue dans la gestion de votre infrastructure de données.  Par conséquent, BlueXP workload factory a été renommée NetApp Workload Factory.



==== Intégration de Ask Me avec MCP

Ask Me, l'assistant IA de Workload Factory, est intégré au protocole de contexte de modèle (MCP).  À l'aide de MCP, Ask Me s'interface en toute sécurité avec des environnements externes et interroge les outils API pour fournir des réponses adaptées à votre environnement de stockage spécifique.



=== 05 octobre 2025



==== Nouvelle notification pour le stockage

Le service de notification NetApp Workload Factory inclut la notification des problèmes bien architecturés pour le stockage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifications pour NetApp Workload Factory"]



=== 09 septembre 2025



==== Nouvelle notification pour le stockage

Le service de notification BlueXP workload factory inclut la notification pour la gestion automatique de la capacité de stockage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifications pour BlueXP workload factory"]
