= Exclure les chemins de fichiers des alertes de comportement utilisateur
:allow-uri-read: 




[[exclude-file-paths-from-user-behavior-alerts]]
=== Exclure les chemins de fichiers des alertes de comportement utilisateur

Ransomware Resilience permet d'exclure certains chemins d'accès aux fichiers des alertes de surveillance du comportement des utilisateurs. Vous pouvez exclure des chemins d'accès si vous savez qu'ils ne sont pas à risque ou si vous effectuez des opérations sur des fichiers dans un volume susceptible de déclencher des alertes.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Exclure les chemins de fichiers des alertes"^].



[[arm-template-for-microsoft-sentinel]]
=== Modèle ARM pour Microsoft Sentinel

Ransomware Resilience propose désormais un modèle Azure Resource Manager (ARM) pour la connexion à Microsoft Sentinel en tant que SIEM, offrant une méthode secondaire pour faciliter le déploiement.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Connectez-vous à un SIEM pour la détection et l'analyse des menaces"^].
