= Améliorations des rapports d'utilisation
:allow-uri-read: 




=== Améliorations des rapports d'utilisation

Plusieurs améliorations des rapports d’utilisation de Cloud Volumes ONTAP sont désormais disponibles :

* L'unité TiB est désormais incluse dans le nom des colonnes.
* Un nouveau champ _node(s)_ pour les numéros de série est désormais inclus.
* Une nouvelle colonne _Type de charge de travail_ est désormais incluse dans le rapport d’utilisation des machines virtuelles de stockage.
* Les noms d’environnement de travail sont désormais inclus dans les rapports d’utilisation des machines virtuelles de stockage et des volumes.
* Le type de volume _fichier_ est désormais étiqueté _Primaire (lecture/écriture)_.
* Le type de volume _secondaire_ est désormais étiqueté _Secondaire (DP)_.


Pour plus d'informations sur les rapports d'utilisation, reportez-vous à https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Télécharger les rapports d'utilisation"] .
