= Une prise en charge a été ajoutée pour sauvegarder les volumes dans des buckets sur les systèmes ONTAP configurés par S3
:allow-uri-read: 


[IMPORTANT]
====
* En raison d’une amélioration de sécurité importante, votre connecteur nécessite désormais un accès Internet sortant vers un point de terminaison supplémentaire afin de gérer les ressources de sauvegarde et de récupération au sein de votre environnement de cloud public.  Si ce point de terminaison n'a pas été ajouté à la liste « autorisée » de votre pare-feu, vous verrez une erreur dans l'interface utilisateur indiquant « Service indisponible » ou « Échec de la détermination de l'état du service » :
+
\ https://netapp-cloud-account.auth0.com

* Un abonnement PAYGO de sauvegarde et de récupération est désormais requis lorsque vous utilisez le package « CVO Professional » qui vous permet de regrouper la sauvegarde et la récupération Cloud Volumes ONTAP et BlueXP backup and recovery.  Cela n’était pas nécessaire dans le passé.  Aucun frais ne sera facturé pour l'abonnement de sauvegarde et de récupération pour les systèmes Cloud Volumes ONTAP éligibles, mais il est requis lors de la configuration de la sauvegarde sur tout nouveau volume.


====


=== Une prise en charge a été ajoutée pour sauvegarder les volumes dans des buckets sur les systèmes ONTAP configurés par S3

Vous pouvez désormais utiliser un système ONTAP configuré pour le service de stockage simple (S3) pour sauvegarder des volumes sur un stockage d'objets.  Ceci est pris en charge pour les systèmes ONTAP sur site et les systèmes Cloud Volumes ONTAP .  Cette configuration est prise en charge dans les déploiements cloud et dans les emplacements sur site sans accès Internet (déploiement en mode « privé »).

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Apprendre encore plus"] .



=== Vous pouvez désormais inclure des instantanés existants d'un volume protégé dans vos fichiers de sauvegarde

Par le passé, vous aviez la possibilité d'inclure des copies Snapshot existantes à partir de volumes en lecture-écriture dans votre fichier de sauvegarde initial vers le stockage d'objets (au lieu de commencer par la copie Snapshot la plus récente).  Les copies Snapshot existantes provenant de volumes en lecture seule (volumes de protection des données) n'ont pas été incluses dans le fichier de sauvegarde.  Vous pouvez désormais choisir d'inclure des copies Snapshot plus anciennes dans le fichier de sauvegarde pour les volumes « DP ».

L'assistant de sauvegarde affiche une invite à la fin des étapes de sauvegarde où vous pouvez sélectionner ces « instantanés existants ».



=== La BlueXP backup and recovery ne prennent plus en charge la sauvegarde automatique des volumes ajoutés ultérieurement

Auparavant, vous pouviez cocher une case dans l’assistant de sauvegarde pour appliquer la politique de sauvegarde sélectionnée à tous les futurs volumes ajoutés au cluster.  Cette fonctionnalité a été supprimée en fonction des commentaires des utilisateurs et du manque d'utilisation de cette fonctionnalité.  Vous devrez activer manuellement les sauvegardes pour tous les nouveaux volumes ajoutés au cluster.



=== La page Suivi des tâches a été mise à jour avec de nouvelles fonctionnalités

La page Surveillance des tâches fournit désormais plus d’informations sur la stratégie de sauvegarde 3-2-1.  Le service fournit également des notifications d’alerte supplémentaires liées à la stratégie de sauvegarde.

Le filtre de type « Cycle de vie de la sauvegarde » a été renommé « Rétention ».  Utilisez ce filtre pour suivre le cycle de vie de la sauvegarde et identifier l’expiration de toutes les copies de sauvegarde.  Le type de tâche « Rétention » capture toutes les tâches de suppression de snapshots lancées sur un volume protégé par la BlueXP backup and recovery.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["En savoir plus sur le Job Monitor mis à jour"] .
