= Nouvelle gestion des politiques pour les données ONTAP
:allow-uri-read: 




=== Nouvelle gestion des politiques pour les données ONTAP

Cette version inclut la possibilité, au sein de l'interface utilisateur, de créer des politiques de snapshot personnalisées, des politiques de réplication et des politiques de sauvegarde sur le stockage d'objets pour les données ONTAP .

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["En savoir plus sur les politiques"] .



=== Prise en charge de la restauration de fichiers et de dossiers à partir de volumes dans le stockage d'objets ONTAP S3

Auparavant, vous ne pouviez pas restaurer les fichiers et les dossiers à l’aide de la fonction « Parcourir et restaurer » lorsque les volumes étaient sauvegardés sur le stockage d’objets ONTAP S3.  Cette version supprime cette restriction.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["En savoir plus sur la restauration des données"] .



=== Possibilité d'archiver immédiatement les données de sauvegarde au lieu de les écrire d'abord sur le stockage standard

Vous pouvez désormais envoyer immédiatement vos fichiers de sauvegarde vers un stockage d'archives au lieu d'écrire les données sur un stockage cloud standard.  Cela peut être particulièrement utile pour les utilisateurs qui ont rarement besoin d’accéder aux données des sauvegardes cloud ou pour les utilisateurs qui remplacent un environnement de sauvegarde sur bande.



=== Prise en charge supplémentaire pour la sauvegarde et la restauration des volumes SnapLock

La sauvegarde et la récupération peuvent désormais sauvegarder les volumes FlexVol et FlexGroup configurés à l'aide des modes de protection SnapLock Compliance ou SnapLock Enterprise .  Vos clusters doivent exécuter ONTAP 9.14 ou une version ultérieure pour cette prise en charge.  La sauvegarde des volumes FlexVol à l'aide du mode SnapLock Enterprise est prise en charge depuis la version 9.11.1 ONTAP .  Les versions antérieures ONTAP ne fournissent aucune prise en charge pour la sauvegarde des volumes de protection SnapLock .

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["En savoir plus sur la protection des données ONTAP"] .
